// Package homunculus owns the on-disk layout the threecorp ECC reference
// implementation pins as
// ~/.local/share/ecc-homunculus/. bough mirrors the shape under a
// separate namespace (~/.local/share/bough-homunculus/) so the two
// systems can coexist on the same machine without stepping on each
// other (= v0.7.2 ECC import doc, round-1 anti-pattern #5).
//
// The directory schema is the contract the rest of the host code
// reads / writes against, so changes here propagate everywhere. Pin
// the layout at v0.9.0 and migrate forward; never silently rename.
package homunculus

import (
	"fmt"
	"os"
	"path/filepath"
)

// DefaultDirEnv overrides the canonical homunculus root for tests
// and for operators who want to relocate the corpus (= sibling vol,
// per-laptop SSD, etc.). When unset the resolver picks the canonical
// path under $HOME.
const DefaultDirEnv = "BOUGH_HOMUNCULUS_DIR"

// Layout pins the on-disk paths under one homunculus root. The
// canonical instance is per-host (= single root per laptop / CI
// runner); per-project subtrees live under Layout.ProjectDir(pid).
type Layout struct {
	Root string
}

// NewLayout returns the canonical Layout. Resolution order:
//
//  1. $BOUGH_HOMUNCULUS_DIR if set and non-empty
//  2. $XDG_DATA_HOME/bough-homunculus if XDG_DATA_HOME is set
//  3. $HOME/.local/share/bough-homunculus
//
// Missing $HOME falls back to /tmp/bough-homunculus so tests in
// hermetic containers do not crash; the caller can override via
// $BOUGH_HOMUNCULUS_DIR.
func NewLayout() Layout {
	return Layout{Root: resolveRoot()}
}

// FromRoot returns a Layout pinned to an explicit root. Tests use
// this to point at a t.TempDir() without touching the real corpus.
func FromRoot(root string) Layout { return Layout{Root: root} }

// ProjectsJSON is the registry file mapping project hash → metadata.
// Matches the ECC reference shape (= {hash: {root, name, remote,
// last_seen, created_at}}).
func (l Layout) ProjectsJSON() string { return filepath.Join(l.Root, "projects.json") }

// ProjectDir is the per-project subtree where instincts /
// observations / evolved artifacts live.
func (l Layout) ProjectDir(projectID string) string {
	return filepath.Join(l.Root, "projects", projectID)
}

// InstinctsDir is the project-scope personal instincts dir
// (= one .md per observed instinct, kebab-case slug = filename = id).
func (l Layout) InstinctsDir(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "instincts", "personal")
}

// InheritedDir holds instincts promoted from global scope into this
// project's namespace via `bough instinct promote`.
func (l Layout) InheritedDir(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "instincts", "inherited")
}

// StagingDir is where the observer writes a freshly minted instinct
// BEFORE the generation gate has cleared it. It is a sibling of
// InstinctsDir under instincts/, so a ScanInstincts of the personal
// dir never descends into it: staging is invisible to injection by
// construction, which is what closes the "live before check" window
// (a minted note cannot be injected until the gate moves it to
// InstinctsDir). The leading dot keeps it out of casual `ls`.
func (l Layout) StagingDir(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "instincts", ".staging")
}

// QuarantineDir holds notes the policy gate HELD, moved here whole
// (never deleted) so an operator can inspect what was withheld, why,
// and put it back. Batches land in dated subdirectories with a
// REPORT.md; a silent hold would be indistinguishable from data loss,
// so surfacing is part of the mechanism, not an add-on.
func (l Layout) QuarantineDir(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "instincts", ".policy-quarantine")
}

// ObservationsFile is the JSONL trail bough hook handle appends to
// from PreToolUse / PostToolUse / Stop hooks. observer-loop reads
// the tail of this file.
func (l Layout) ObservationsFile(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "observations.jsonl")
}

// ObserverLog is the daemon's append-only log. bough doctor surfaces
// the tail.
func (l Layout) ObserverLog(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "observer.log")
}

// ClusterLabels is the evolve catalog (= {label: description} map).
// `/evolve-skill-manual-v3` reads / mutates this file atomically.
func (l Layout) ClusterLabels(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "cluster-labels.json")
}

// EvolvedSkillsDir holds <slug>/SKILL.md trees generated by the
// 5-gate evolve pipeline. ~/.claude/skills/<slug> typically symlinks
// here.
func (l Layout) EvolvedSkillsDir(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "evolved", "skills")
}

// EvolvedAgentsDir holds <slug>.md agent specs from the agent +
// command evolve pass.
func (l Layout) EvolvedAgentsDir(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "evolved", "agents")
}

// EvolvedCommandsDir holds <slug>.md slash-command specs.
func (l Layout) EvolvedCommandsDir(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "evolved", "commands")
}

// EvalDir holds per-session score jsonl (= eval/scores.jsonl) the
// SessionEnd handler appends to.
func (l Layout) EvalDir(projectID string) string {
	return filepath.Join(l.ProjectDir(projectID), "eval")
}

// GlobalInstinctsDir holds cross-project instincts (= scope=global).
func (l Layout) GlobalInstinctsDir() string {
	return filepath.Join(l.Root, "instincts", "personal")
}

// EnsureProjectDirs creates every per-project subtree the host
// expects. Safe to call repeatedly (= idempotent mkdir -p).
func (l Layout) EnsureProjectDirs(projectID string) error {
	dirs := []string{
		l.InstinctsDir(projectID),
		l.StagingDir(projectID),
		l.InheritedDir(projectID),
		l.EvolvedSkillsDir(projectID),
		l.EvolvedAgentsDir(projectID),
		l.EvolvedCommandsDir(projectID),
		l.EvalDir(projectID),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return fmt.Errorf("homunculus: mkdir %s: %w", d, err)
		}
	}
	return nil
}

// EnsureGlobalDirs creates the top-level + global instincts dirs so
// the registry write does not race against missing parents.
func (l Layout) EnsureGlobalDirs() error {
	dirs := []string{l.Root, l.GlobalInstinctsDir()}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0o755); err != nil {
			return fmt.Errorf("homunculus: mkdir %s: %w", d, err)
		}
	}
	return nil
}

func resolveRoot() string {
	if v := os.Getenv(DefaultDirEnv); v != "" {
		return v
	}
	if v := os.Getenv("XDG_DATA_HOME"); v != "" {
		return filepath.Join(v, "bough-homunculus")
	}
	if home, err := os.UserHomeDir(); err == nil && home != "" {
		return filepath.Join(home, ".local", "share", "bough-homunculus")
	}
	return filepath.Join(os.TempDir(), "bough-homunculus")
}
