// memory.proto is the v0.5.0 contract between the bough host and any
// `bough-plugin-memory-<name>` binary that persists, queries, and
// audits per-worktree instinct state. Plugins implement MemoryBackend
// over Hashicorp go-plugin's gRPC transport.
//
// bough does NOT own memory intelligence. The SQLite reference-
// fallback backend ships in v0.5 only as the minimum protocol-
// verification implementation; production deployments are expected to
// configure mem0 / Graphiti / Letta via separate community / official
// plugins (v0.6+). See docs/EXTERNAL_MEMORY_BACKENDS.md.
//
// Versioning: bumping ProtocolVersion in plugins/memory/api/handshake.go
// is what gates a backwards-incompatible change here. Add new fields
// with new tag numbers, do not renumber existing ones. v0.6 will add
// optional features (semantic query, graph query, vector search)
// negotiated through the Capabilities() RPC — plugins should reply
// `false` for any feature they have not implemented rather than
// erroring at Query time.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: memory.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryBackend_Health_FullMethodName       = "/bough.memory.v1.MemoryBackend/Health"
	MemoryBackend_Capabilities_FullMethodName = "/bough.memory.v1.MemoryBackend/Capabilities"
	MemoryBackend_Store_FullMethodName        = "/bough.memory.v1.MemoryBackend/Store"
	MemoryBackend_Query_FullMethodName        = "/bough.memory.v1.MemoryBackend/Query"
	MemoryBackend_Forget_FullMethodName       = "/bough.memory.v1.MemoryBackend/Forget"
	MemoryBackend_Export_FullMethodName       = "/bough.memory.v1.MemoryBackend/Export"
	MemoryBackend_Import_FullMethodName       = "/bough.memory.v1.MemoryBackend/Import"
)

// MemoryBackendClient is the client API for MemoryBackend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MemoryBackend persists and retrieves the instincts produced by the
// host's InstinctMinter pipeline. The backend is intentionally NOT
// asked to mint, compile, or evaluate — those belong to other
// interfaces (InstinctMinter / CapabilityCompiler / SkillEvaluator).
type MemoryBackendClient interface {
	// Health is a lightweight liveness probe used during pluginhost
	// discovery and conformance lifecycle. Plugins should answer in
	// under ~50ms with their backend kind and reachability state.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// Capabilities lets a plugin advertise its optional feature support
	// (vector search, graph query, semantic query, bulk export, ...).
	// The host uses this to decide whether to route a given Query to
	// the plugin or to fall back to FTS. v0.5 plugins should return all
	// optional features as `false`.
	Capabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error)
	// Store persists or upserts a single Instinct. The host treats
	// Store as a true upsert: if an item with the same ID (or matching
	// DedupeKey within the same scope) already exists, the backend
	// increments hits, updates confidence according to source policy,
	// and refreshes last_hit_at. Stdin-ingest and JSONL-tail observers
	// can both retry-fire the same SourceEventID; the backend must
	// dedupe on (DedupeKey, SourceEventID) to keep CI retries and JSONL
	// re-reads idempotent.
	Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error)
	// Query searches the backend for instincts matching Term within
	// Scope, bounded by both MaxResults (count cap) and MaxTokens
	// (estimated-token cap). The backend MUST honor both caps and set
	// Truncated=true on each Result that was elided. EstimatedTokens
	// lets the host's budget aggregator stop iterating once the
	// running total exceeds the configured retrieve.max_tokens.
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Forget is a soft delete: the backend marks the instinct's State
	// as "forgotten" but keeps the row for audit. Hard deletion is the
	// responsibility of the coordinator's decay scheduler, not the
	// backend.
	Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*ForgetResponse, error)
	// Export streams the backend's instincts out in the requested
	// format. v0.5 supports "yaml" and "jsonl"; v0.6+ adds
	// "claude-skills", "agent-skill", and "mcp".
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// Import re-hydrates instincts from a previously Exported payload.
	// The backend should treat Import as a batch of upserts (same
	// dedupe semantics as Store).
	Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResponse, error)
}

type memoryBackendClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryBackendClient(cc grpc.ClientConnInterface) MemoryBackendClient {
	return &memoryBackendClient{cc}
}

func (c *memoryBackendClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, MemoryBackend_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryBackendClient) Capabilities(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CapabilitiesResponse)
	err := c.cc.Invoke(ctx, MemoryBackend_Capabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryBackendClient) Store(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*StoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreResponse)
	err := c.cc.Invoke(ctx, MemoryBackend_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryBackendClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, MemoryBackend_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryBackendClient) Forget(ctx context.Context, in *ForgetRequest, opts ...grpc.CallOption) (*ForgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetResponse)
	err := c.cc.Invoke(ctx, MemoryBackend_Forget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryBackendClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, MemoryBackend_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryBackendClient) Import(ctx context.Context, in *ImportRequest, opts ...grpc.CallOption) (*ImportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportResponse)
	err := c.cc.Invoke(ctx, MemoryBackend_Import_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryBackendServer is the server API for MemoryBackend service.
// All implementations must embed UnimplementedMemoryBackendServer
// for forward compatibility.
//
// MemoryBackend persists and retrieves the instincts produced by the
// host's InstinctMinter pipeline. The backend is intentionally NOT
// asked to mint, compile, or evaluate — those belong to other
// interfaces (InstinctMinter / CapabilityCompiler / SkillEvaluator).
type MemoryBackendServer interface {
	// Health is a lightweight liveness probe used during pluginhost
	// discovery and conformance lifecycle. Plugins should answer in
	// under ~50ms with their backend kind and reachability state.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// Capabilities lets a plugin advertise its optional feature support
	// (vector search, graph query, semantic query, bulk export, ...).
	// The host uses this to decide whether to route a given Query to
	// the plugin or to fall back to FTS. v0.5 plugins should return all
	// optional features as `false`.
	Capabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error)
	// Store persists or upserts a single Instinct. The host treats
	// Store as a true upsert: if an item with the same ID (or matching
	// DedupeKey within the same scope) already exists, the backend
	// increments hits, updates confidence according to source policy,
	// and refreshes last_hit_at. Stdin-ingest and JSONL-tail observers
	// can both retry-fire the same SourceEventID; the backend must
	// dedupe on (DedupeKey, SourceEventID) to keep CI retries and JSONL
	// re-reads idempotent.
	Store(context.Context, *StoreRequest) (*StoreResponse, error)
	// Query searches the backend for instincts matching Term within
	// Scope, bounded by both MaxResults (count cap) and MaxTokens
	// (estimated-token cap). The backend MUST honor both caps and set
	// Truncated=true on each Result that was elided. EstimatedTokens
	// lets the host's budget aggregator stop iterating once the
	// running total exceeds the configured retrieve.max_tokens.
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Forget is a soft delete: the backend marks the instinct's State
	// as "forgotten" but keeps the row for audit. Hard deletion is the
	// responsibility of the coordinator's decay scheduler, not the
	// backend.
	Forget(context.Context, *ForgetRequest) (*ForgetResponse, error)
	// Export streams the backend's instincts out in the requested
	// format. v0.5 supports "yaml" and "jsonl"; v0.6+ adds
	// "claude-skills", "agent-skill", and "mcp".
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	// Import re-hydrates instincts from a previously Exported payload.
	// The backend should treat Import as a batch of upserts (same
	// dedupe semantics as Store).
	Import(context.Context, *ImportRequest) (*ImportResponse, error)
	mustEmbedUnimplementedMemoryBackendServer()
}

// UnimplementedMemoryBackendServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryBackendServer struct{}

func (UnimplementedMemoryBackendServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedMemoryBackendServer) Capabilities(context.Context, *emptypb.Empty) (*CapabilitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Capabilities not implemented")
}
func (UnimplementedMemoryBackendServer) Store(context.Context, *StoreRequest) (*StoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedMemoryBackendServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedMemoryBackendServer) Forget(context.Context, *ForgetRequest) (*ForgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Forget not implemented")
}
func (UnimplementedMemoryBackendServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedMemoryBackendServer) Import(context.Context, *ImportRequest) (*ImportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Import not implemented")
}
func (UnimplementedMemoryBackendServer) mustEmbedUnimplementedMemoryBackendServer() {}
func (UnimplementedMemoryBackendServer) testEmbeddedByValue()                       {}

// UnsafeMemoryBackendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryBackendServer will
// result in compilation errors.
type UnsafeMemoryBackendServer interface {
	mustEmbedUnimplementedMemoryBackendServer()
}

func RegisterMemoryBackendServer(s grpc.ServiceRegistrar, srv MemoryBackendServer) {
	// If the following call panics, it indicates UnimplementedMemoryBackendServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryBackend_ServiceDesc, srv)
}

func _MemoryBackend_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryBackendServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryBackend_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryBackendServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryBackend_Capabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryBackendServer).Capabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryBackend_Capabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryBackendServer).Capabilities(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryBackend_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryBackendServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryBackend_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryBackendServer).Store(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryBackend_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryBackendServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryBackend_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryBackendServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryBackend_Forget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryBackendServer).Forget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryBackend_Forget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryBackendServer).Forget(ctx, req.(*ForgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryBackend_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryBackendServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryBackend_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryBackendServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryBackend_Import_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryBackendServer).Import(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryBackend_Import_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryBackendServer).Import(ctx, req.(*ImportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryBackend_ServiceDesc is the grpc.ServiceDesc for MemoryBackend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryBackend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bough.memory.v1.MemoryBackend",
	HandlerType: (*MemoryBackendServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Health",
			Handler:    _MemoryBackend_Health_Handler,
		},
		{
			MethodName: "Capabilities",
			Handler:    _MemoryBackend_Capabilities_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _MemoryBackend_Store_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _MemoryBackend_Query_Handler,
		},
		{
			MethodName: "Forget",
			Handler:    _MemoryBackend_Forget_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _MemoryBackend_Export_Handler,
		},
		{
			MethodName: "Import",
			Handler:    _MemoryBackend_Import_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "memory.proto",
}
