// memory.proto is the v0.5.0 contract between the bough host and any
// `bough-plugin-memory-<name>` binary that persists, queries, and
// audits per-worktree instinct state. Plugins implement MemoryBackend
// over Hashicorp go-plugin's gRPC transport.
//
// bough does NOT own memory intelligence. The SQLite reference-
// fallback backend ships in v0.5 only as the minimum protocol-
// verification implementation; production deployments are expected to
// configure mem0 / Graphiti / Letta via separate community / official
// plugins (v0.6+). See docs/EXTERNAL_MEMORY_BACKENDS.md.
//
// Versioning: bumping ProtocolVersion in plugins/memory/api/handshake.go
// is what gates a backwards-incompatible change here. Add new fields
// with new tag numbers, do not renumber existing ones. v0.6 will add
// optional features (semantic query, graph query, vector search)
// negotiated through the Capabilities() RPC — plugins should reply
// `false` for any feature they have not implemented rather than
// erroring at Query time.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: memory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scope addresses one of three lifetime tiers. WorktreeID is set only
// for Level="worktree"; RepoName is set for Level="repo" and
// Level="global". The host's promote.go controller is what moves an
// instinct between tiers — backends never invent or change scope.
type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "worktree" | "repo" | "global"
	WorktreeId    string                 `protobuf:"bytes,2,opt,name=worktree_id,json=worktreeId,proto3" json:"worktree_id,omitempty"`
	RepoName      string                 `protobuf:"bytes,3,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Scope) GetWorktreeId() string {
	if x != nil {
		return x.WorktreeId
	}
	return ""
}

func (x *Scope) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

// Instinct is the active row carried by the backend. The fields
// mirror pkg/schema/Instinct (CapabilityArtifact stays out of memory
// land — it is a compiled artifact owned by CapabilityCompiler).
type Instinct struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rule         string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Why          string                 `protobuf:"bytes,3,opt,name=why,proto3" json:"why,omitempty"`
	HowToApply   string                 `protobuf:"bytes,4,opt,name=how_to_apply,json=howToApply,proto3" json:"how_to_apply,omitempty"`
	Domain       []string               `protobuf:"bytes,5,rep,name=domain,proto3" json:"domain,omitempty"`
	Scope        *Scope                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Source       string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"` // explicit_user_feedback | test_failure | session_summary | llm_only | ...
	Confidence   float64                `protobuf:"fixed64,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	State        string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"` // candidate | active | archived | forgotten
	Hits         int32                  `protobuf:"varint,10,opt,name=hits,proto3" json:"hits,omitempty"`
	LastHitAt    int64                  `protobuf:"varint,11,opt,name=last_hit_at,json=lastHitAt,proto3" json:"last_hit_at,omitempty"` // unix epoch seconds
	CreatedAt    int64                  `protobuf:"varint,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SourceTraces []string               `protobuf:"bytes,13,rep,name=source_traces,json=sourceTraces,proto3" json:"source_traces,omitempty"`
	EvidenceRefs []string               `protobuf:"bytes,14,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	DedupeKey    string                 `protobuf:"bytes,15,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"` // sha256(normalize(rule + scope))
	// metadata holds plugin-defined JSON (mcp resource_template,
	// skill frontmatter, ...). v0.5 SQLite reserves the column so
	// v0.6 plugins can populate it without a schema migration.
	MetadataJson  string `protobuf:"bytes,16,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instinct) Reset() {
	*x = Instinct{}
	mi := &file_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instinct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instinct) ProtoMessage() {}

func (x *Instinct) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instinct.ProtoReflect.Descriptor instead.
func (*Instinct) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{1}
}

func (x *Instinct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Instinct) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *Instinct) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

func (x *Instinct) GetHowToApply() string {
	if x != nil {
		return x.HowToApply
	}
	return ""
}

func (x *Instinct) GetDomain() []string {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *Instinct) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *Instinct) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Instinct) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Instinct) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Instinct) GetHits() int32 {
	if x != nil {
		return x.Hits
	}
	return 0
}

func (x *Instinct) GetLastHitAt() int64 {
	if x != nil {
		return x.LastHitAt
	}
	return 0
}

func (x *Instinct) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Instinct) GetSourceTraces() []string {
	if x != nil {
		return x.SourceTraces
	}
	return nil
}

func (x *Instinct) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *Instinct) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *Instinct) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{2}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	BackendKind   string                 `protobuf:"bytes,2,opt,name=backend_kind,json=backendKind,proto3" json:"backend_kind,omitempty"` // "sqlite" | "mem0" | "graphiti" | ...
	PluginVersion string                 `protobuf:"bytes,3,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{3}
}

func (x *HealthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *HealthResponse) GetBackendKind() string {
	if x != nil {
		return x.BackendKind
	}
	return ""
}

func (x *HealthResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

type CapabilitiesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SemanticQuery    bool                   `protobuf:"varint,1,opt,name=semantic_query,json=semanticQuery,proto3" json:"semantic_query,omitempty"`          // dense vector + reranker (v0.6+)
	GraphQuery       bool                   `protobuf:"varint,2,opt,name=graph_query,json=graphQuery,proto3" json:"graph_query,omitempty"`                   // entity / relation query (v0.6+)
	BulkExport       bool                   `protobuf:"varint,3,opt,name=bulk_export,json=bulkExport,proto3" json:"bulk_export,omitempty"`                   // streaming export (v0.6+)
	VectorSearch     bool                   `protobuf:"varint,4,opt,name=vector_search,json=vectorSearch,proto3" json:"vector_search,omitempty"`             // pure ANN backend (v0.6+)
	SupportsMetadata bool                   `protobuf:"varint,5,opt,name=supports_metadata,json=supportsMetadata,proto3" json:"supports_metadata,omitempty"` // honors Instinct.metadata_json
	PluginVersion    string                 `protobuf:"bytes,6,opt,name=plugin_version,json=pluginVersion,proto3" json:"plugin_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CapabilitiesResponse) Reset() {
	*x = CapabilitiesResponse{}
	mi := &file_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitiesResponse) ProtoMessage() {}

func (x *CapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*CapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{4}
}

func (x *CapabilitiesResponse) GetSemanticQuery() bool {
	if x != nil {
		return x.SemanticQuery
	}
	return false
}

func (x *CapabilitiesResponse) GetGraphQuery() bool {
	if x != nil {
		return x.GraphQuery
	}
	return false
}

func (x *CapabilitiesResponse) GetBulkExport() bool {
	if x != nil {
		return x.BulkExport
	}
	return false
}

func (x *CapabilitiesResponse) GetVectorSearch() bool {
	if x != nil {
		return x.VectorSearch
	}
	return false
}

func (x *CapabilitiesResponse) GetSupportsMetadata() bool {
	if x != nil {
		return x.SupportsMetadata
	}
	return false
}

func (x *CapabilitiesResponse) GetPluginVersion() string {
	if x != nil {
		return x.PluginVersion
	}
	return ""
}

type StoreRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Instinct        *Instinct              `protobuf:"bytes,1,opt,name=instinct,proto3" json:"instinct,omitempty"`
	DedupeKey       string                 `protobuf:"bytes,2,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"`                    // sha256(normalize(rule + scope)); host may pre-compute
	SourceEventId   string                 `protobuf:"bytes,3,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`      // CI / JSONL tail / retry idempotency token
	UpsertSemantics bool                   `protobuf:"varint,4,opt,name=upsert_semantics,json=upsertSemantics,proto3" json:"upsert_semantics,omitempty"` // true: existing ID → hits++ / confidence reinforce
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{5}
}

func (x *StoreRequest) GetInstinct() *Instinct {
	if x != nil {
		return x.Instinct
	}
	return nil
}

func (x *StoreRequest) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

func (x *StoreRequest) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *StoreRequest) GetUpsertSemantics() bool {
	if x != nil {
		return x.UpsertSemantics
	}
	return false
}

type StoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	StoredId      string                 `protobuf:"bytes,2,opt,name=stored_id,json=storedId,proto3" json:"stored_id,omitempty"`
	WasUpsert     bool                   `protobuf:"varint,3,opt,name=was_upsert,json=wasUpsert,proto3" json:"was_upsert,omitempty"` // true if existing row updated, false if new row inserted
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreResponse) Reset() {
	*x = StoreResponse{}
	mi := &file_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreResponse) ProtoMessage() {}

func (x *StoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreResponse.ProtoReflect.Descriptor instead.
func (*StoreResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{6}
}

func (x *StoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *StoreResponse) GetStoredId() string {
	if x != nil {
		return x.StoredId
	}
	return ""
}

func (x *StoreResponse) GetWasUpsert() bool {
	if x != nil {
		return x.WasUpsert
	}
	return false
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          string                 `protobuf:"bytes,1,opt,name=term,proto3" json:"term,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	MaxResults    int32                  `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"` // host-imposed hard limit (validator default 12)
	MaxTokens     int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`    // host-imposed hard limit (validator default 4000)
	MinConfidence float64                `protobuf:"fixed64,5,opt,name=min_confidence,json=minConfidence,proto3" json:"min_confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{7}
}

func (x *QueryRequest) GetTerm() string {
	if x != nil {
		return x.Term
	}
	return ""
}

func (x *QueryRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *QueryRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *QueryRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *QueryRequest) GetMinConfidence() float64 {
	if x != nil {
		return x.MinConfidence
	}
	return 0
}

type QueryResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Instinct        *Instinct              `protobuf:"bytes,1,opt,name=instinct,proto3" json:"instinct,omitempty"`
	Score           float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	EstimatedTokens int32                  `protobuf:"varint,3,opt,name=estimated_tokens,json=estimatedTokens,proto3" json:"estimated_tokens,omitempty"` // backend's best estimate; host aggregates
	Truncated       bool                   `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`                                    // true if max_tokens cap elided content
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{8}
}

func (x *QueryResult) GetInstinct() *Instinct {
	if x != nil {
		return x.Instinct
	}
	return nil
}

func (x *QueryResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *QueryResult) GetEstimatedTokens() int32 {
	if x != nil {
		return x.EstimatedTokens
	}
	return 0
}

func (x *QueryResult) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Results       []*QueryResult         `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{9}
}

func (x *QueryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *QueryResponse) GetResults() []*QueryResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type ForgetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetRequest) Reset() {
	*x = ForgetRequest{}
	mi := &file_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetRequest) ProtoMessage() {}

func (x *ForgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetRequest.ProtoReflect.Descriptor instead.
func (*ForgetRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{10}
}

func (x *ForgetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ForgetRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ForgetRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ForgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetResponse) Reset() {
	*x = ForgetResponse{}
	mi := &file_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetResponse) ProtoMessage() {}

func (x *ForgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetResponse.ProtoReflect.Descriptor instead.
func (*ForgetResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{11}
}

func (x *ForgetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`                              // "yaml" | "jsonl"  (v0.6: + "claude-skills" / "agent-skill" / "mcp")
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`                                // empty Level = all scopes
	StateFilter   string                 `protobuf:"bytes,3,opt,name=state_filter,json=stateFilter,proto3" json:"state_filter,omitempty"` // "" = all; otherwise "active" | "candidate" | ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{12}
}

func (x *ExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *ExportRequest) GetStateFilter() string {
	if x != nil {
		return x.StateFilter
	}
	return ""
}

type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{13}
}

func (x *ExportResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExportResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ExportResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ImportRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Format            string                 `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
	Payload           []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	OverwriteExisting bool                   `protobuf:"varint,3,opt,name=overwrite_existing,json=overwriteExisting,proto3" json:"overwrite_existing,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ImportRequest) Reset() {
	*x = ImportRequest{}
	mi := &file_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRequest) ProtoMessage() {}

func (x *ImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRequest.ProtoReflect.Descriptor instead.
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{14}
}

func (x *ImportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ImportRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ImportRequest) GetOverwriteExisting() bool {
	if x != nil {
		return x.OverwriteExisting
	}
	return false
}

type ImportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ImportedCount int32                  `protobuf:"varint,2,opt,name=imported_count,json=importedCount,proto3" json:"imported_count,omitempty"`
	UpsertedCount int32                  `protobuf:"varint,3,opt,name=upserted_count,json=upsertedCount,proto3" json:"upserted_count,omitempty"`
	SkippedCount  int32                  `protobuf:"varint,4,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResponse) Reset() {
	*x = ImportResponse{}
	mi := &file_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResponse) ProtoMessage() {}

func (x *ImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResponse.ProtoReflect.Descriptor instead.
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return file_memory_proto_rawDescGZIP(), []int{15}
}

func (x *ImportResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ImportResponse) GetImportedCount() int32 {
	if x != nil {
		return x.ImportedCount
	}
	return 0
}

func (x *ImportResponse) GetUpsertedCount() int32 {
	if x != nil {
		return x.UpsertedCount
	}
	return 0
}

func (x *ImportResponse) GetSkippedCount() int32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

var File_memory_proto protoreflect.FileDescriptor

const file_memory_proto_rawDesc = "" +
	"\n" +
	"\fmemory.proto\x12\x0fbough.memory.v1\x1a\x1bgoogle/protobuf/empty.proto\"[\n" +
	"\x05Scope\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1f\n" +
	"\vworktree_id\x18\x02 \x01(\tR\n" +
	"worktreeId\x12\x1b\n" +
	"\trepo_name\x18\x03 \x01(\tR\brepoName\"\xd7\x03\n" +
	"\bInstinct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x10\n" +
	"\x03why\x18\x03 \x01(\tR\x03why\x12 \n" +
	"\fhow_to_apply\x18\x04 \x01(\tR\n" +
	"howToApply\x12\x16\n" +
	"\x06domain\x18\x05 \x03(\tR\x06domain\x12,\n" +
	"\x05scope\x18\x06 \x01(\v2\x16.bough.memory.v1.ScopeR\x05scope\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12\x12\n" +
	"\x04hits\x18\n" +
	" \x01(\x05R\x04hits\x12\x1e\n" +
	"\vlast_hit_at\x18\v \x01(\x03R\tlastHitAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\x03R\tcreatedAt\x12#\n" +
	"\rsource_traces\x18\r \x03(\tR\fsourceTraces\x12#\n" +
	"\revidence_refs\x18\x0e \x03(\tR\fevidenceRefs\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\x0f \x01(\tR\tdedupeKey\x12#\n" +
	"\rmetadata_json\x18\x10 \x01(\tR\fmetadataJson\"\x0f\n" +
	"\rHealthRequest\"p\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12!\n" +
	"\fbackend_kind\x18\x02 \x01(\tR\vbackendKind\x12%\n" +
	"\x0eplugin_version\x18\x03 \x01(\tR\rpluginVersion\"\xf8\x01\n" +
	"\x14CapabilitiesResponse\x12%\n" +
	"\x0esemantic_query\x18\x01 \x01(\bR\rsemanticQuery\x12\x1f\n" +
	"\vgraph_query\x18\x02 \x01(\bR\n" +
	"graphQuery\x12\x1f\n" +
	"\vbulk_export\x18\x03 \x01(\bR\n" +
	"bulkExport\x12#\n" +
	"\rvector_search\x18\x04 \x01(\bR\fvectorSearch\x12+\n" +
	"\x11supports_metadata\x18\x05 \x01(\bR\x10supportsMetadata\x12%\n" +
	"\x0eplugin_version\x18\x06 \x01(\tR\rpluginVersion\"\xb7\x01\n" +
	"\fStoreRequest\x125\n" +
	"\binstinct\x18\x01 \x01(\v2\x19.bough.memory.v1.InstinctR\binstinct\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\x02 \x01(\tR\tdedupeKey\x12&\n" +
	"\x0fsource_event_id\x18\x03 \x01(\tR\rsourceEventId\x12)\n" +
	"\x10upsert_semantics\x18\x04 \x01(\bR\x0fupsertSemantics\"a\n" +
	"\rStoreResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1b\n" +
	"\tstored_id\x18\x02 \x01(\tR\bstoredId\x12\x1d\n" +
	"\n" +
	"was_upsert\x18\x03 \x01(\bR\twasUpsert\"\xb7\x01\n" +
	"\fQueryRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\tR\x04term\x12,\n" +
	"\x05scope\x18\x02 \x01(\v2\x16.bough.memory.v1.ScopeR\x05scope\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\x05R\n" +
	"maxResults\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12%\n" +
	"\x0emin_confidence\x18\x05 \x01(\x01R\rminConfidence\"\xa3\x01\n" +
	"\vQueryResult\x125\n" +
	"\binstinct\x18\x01 \x01(\v2\x19.bough.memory.v1.InstinctR\binstinct\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12)\n" +
	"\x10estimated_tokens\x18\x03 \x01(\x05R\x0festimatedTokens\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\"]\n" +
	"\rQueryResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x126\n" +
	"\aresults\x18\x02 \x03(\v2\x1c.bough.memory.v1.QueryResultR\aresults\"e\n" +
	"\rForgetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x05scope\x18\x02 \x01(\v2\x16.bough.memory.v1.ScopeR\x05scope\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"&\n" +
	"\x0eForgetResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"x\n" +
	"\rExportRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12,\n" +
	"\x05scope\x18\x02 \x01(\v2\x16.bough.memory.v1.ScopeR\x05scope\x12!\n" +
	"\fstate_filter\x18\x03 \x01(\tR\vstateFilter\"c\n" +
	"\x0eExportResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"p\n" +
	"\rImportRequest\x12\x16\n" +
	"\x06format\x18\x01 \x01(\tR\x06format\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12-\n" +
	"\x12overwrite_existing\x18\x03 \x01(\bR\x11overwriteExisting\"\x99\x01\n" +
	"\x0eImportResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12%\n" +
	"\x0eimported_count\x18\x02 \x01(\x05R\rimportedCount\x12%\n" +
	"\x0eupserted_count\x18\x03 \x01(\x05R\rupsertedCount\x12#\n" +
	"\rskipped_count\x18\x04 \x01(\x05R\fskippedCount2\x9a\x04\n" +
	"\rMemoryBackend\x12I\n" +
	"\x06Health\x12\x1e.bough.memory.v1.HealthRequest\x1a\x1f.bough.memory.v1.HealthResponse\x12M\n" +
	"\fCapabilities\x12\x16.google.protobuf.Empty\x1a%.bough.memory.v1.CapabilitiesResponse\x12F\n" +
	"\x05Store\x12\x1d.bough.memory.v1.StoreRequest\x1a\x1e.bough.memory.v1.StoreResponse\x12F\n" +
	"\x05Query\x12\x1d.bough.memory.v1.QueryRequest\x1a\x1e.bough.memory.v1.QueryResponse\x12I\n" +
	"\x06Forget\x12\x1e.bough.memory.v1.ForgetRequest\x1a\x1f.bough.memory.v1.ForgetResponse\x12I\n" +
	"\x06Export\x12\x1e.bough.memory.v1.ExportRequest\x1a\x1f.bough.memory.v1.ExportResponse\x12I\n" +
	"\x06Import\x12\x1e.bough.memory.v1.ImportRequest\x1a\x1f.bough.memory.v1.ImportResponseB;Z9github.com/ikeikeikeike/bough/plugins/memory/api/proto;pbb\x06proto3"

var (
	file_memory_proto_rawDescOnce sync.Once
	file_memory_proto_rawDescData []byte
)

func file_memory_proto_rawDescGZIP() []byte {
	file_memory_proto_rawDescOnce.Do(func() {
		file_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)))
	})
	return file_memory_proto_rawDescData
}

var file_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_memory_proto_goTypes = []any{
	(*Scope)(nil),                // 0: bough.memory.v1.Scope
	(*Instinct)(nil),             // 1: bough.memory.v1.Instinct
	(*HealthRequest)(nil),        // 2: bough.memory.v1.HealthRequest
	(*HealthResponse)(nil),       // 3: bough.memory.v1.HealthResponse
	(*CapabilitiesResponse)(nil), // 4: bough.memory.v1.CapabilitiesResponse
	(*StoreRequest)(nil),         // 5: bough.memory.v1.StoreRequest
	(*StoreResponse)(nil),        // 6: bough.memory.v1.StoreResponse
	(*QueryRequest)(nil),         // 7: bough.memory.v1.QueryRequest
	(*QueryResult)(nil),          // 8: bough.memory.v1.QueryResult
	(*QueryResponse)(nil),        // 9: bough.memory.v1.QueryResponse
	(*ForgetRequest)(nil),        // 10: bough.memory.v1.ForgetRequest
	(*ForgetResponse)(nil),       // 11: bough.memory.v1.ForgetResponse
	(*ExportRequest)(nil),        // 12: bough.memory.v1.ExportRequest
	(*ExportResponse)(nil),       // 13: bough.memory.v1.ExportResponse
	(*ImportRequest)(nil),        // 14: bough.memory.v1.ImportRequest
	(*ImportResponse)(nil),       // 15: bough.memory.v1.ImportResponse
	(*emptypb.Empty)(nil),        // 16: google.protobuf.Empty
}
var file_memory_proto_depIdxs = []int32{
	0,  // 0: bough.memory.v1.Instinct.scope:type_name -> bough.memory.v1.Scope
	1,  // 1: bough.memory.v1.StoreRequest.instinct:type_name -> bough.memory.v1.Instinct
	0,  // 2: bough.memory.v1.QueryRequest.scope:type_name -> bough.memory.v1.Scope
	1,  // 3: bough.memory.v1.QueryResult.instinct:type_name -> bough.memory.v1.Instinct
	8,  // 4: bough.memory.v1.QueryResponse.results:type_name -> bough.memory.v1.QueryResult
	0,  // 5: bough.memory.v1.ForgetRequest.scope:type_name -> bough.memory.v1.Scope
	0,  // 6: bough.memory.v1.ExportRequest.scope:type_name -> bough.memory.v1.Scope
	2,  // 7: bough.memory.v1.MemoryBackend.Health:input_type -> bough.memory.v1.HealthRequest
	16, // 8: bough.memory.v1.MemoryBackend.Capabilities:input_type -> google.protobuf.Empty
	5,  // 9: bough.memory.v1.MemoryBackend.Store:input_type -> bough.memory.v1.StoreRequest
	7,  // 10: bough.memory.v1.MemoryBackend.Query:input_type -> bough.memory.v1.QueryRequest
	10, // 11: bough.memory.v1.MemoryBackend.Forget:input_type -> bough.memory.v1.ForgetRequest
	12, // 12: bough.memory.v1.MemoryBackend.Export:input_type -> bough.memory.v1.ExportRequest
	14, // 13: bough.memory.v1.MemoryBackend.Import:input_type -> bough.memory.v1.ImportRequest
	3,  // 14: bough.memory.v1.MemoryBackend.Health:output_type -> bough.memory.v1.HealthResponse
	4,  // 15: bough.memory.v1.MemoryBackend.Capabilities:output_type -> bough.memory.v1.CapabilitiesResponse
	6,  // 16: bough.memory.v1.MemoryBackend.Store:output_type -> bough.memory.v1.StoreResponse
	9,  // 17: bough.memory.v1.MemoryBackend.Query:output_type -> bough.memory.v1.QueryResponse
	11, // 18: bough.memory.v1.MemoryBackend.Forget:output_type -> bough.memory.v1.ForgetResponse
	13, // 19: bough.memory.v1.MemoryBackend.Export:output_type -> bough.memory.v1.ExportResponse
	15, // 20: bough.memory.v1.MemoryBackend.Import:output_type -> bough.memory.v1.ImportResponse
	14, // [14:21] is the sub-list for method output_type
	7,  // [7:14] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_memory_proto_init() }
func file_memory_proto_init() {
	if File_memory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_memory_proto_rawDesc), len(file_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_memory_proto_goTypes,
		DependencyIndexes: file_memory_proto_depIdxs,
		MessageInfos:      file_memory_proto_msgTypes,
	}.Build()
	File_memory_proto = out.File
	file_memory_proto_goTypes = nil
	file_memory_proto_depIdxs = nil
}
