// db.proto is the contract between the bough host and any
// `bough-plugin-<kind>` binary that provisions a per-worktree database.
// Plugins implement DBProvider over Hashicorp go-plugin's gRPC transport.
//
// Versioning: bumping ProtocolVersion in plugins/db/api/handshake.go is
// what gates a backwards-incompatible change here. Add new fields with
// new tag numbers, do not renumber existing ones.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: db.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Port             int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Datadir          string                 `protobuf:"bytes,2,opt,name=datadir,proto3" json:"datadir,omitempty"`
	WorktreeRoot     string                 `protobuf:"bytes,3,opt,name=worktree_root,json=worktreeRoot,proto3" json:"worktree_root,omitempty"`
	Extras           map[string]string      `protobuf:"bytes,4,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InitialDatabases []string               `protobuf:"bytes,5,rep,name=initial_databases,json=initialDatabases,proto3" json:"initial_databases,omitempty"`
	SocketDir        string                 `protobuf:"bytes,6,opt,name=socket_dir,json=socketDir,proto3" json:"socket_dir,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpRequest) Reset() {
	*x = UpRequest{}
	mi := &file_db_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpRequest) ProtoMessage() {}

func (x *UpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpRequest.ProtoReflect.Descriptor instead.
func (*UpRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{0}
}

func (x *UpRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *UpRequest) GetDatadir() string {
	if x != nil {
		return x.Datadir
	}
	return ""
}

func (x *UpRequest) GetWorktreeRoot() string {
	if x != nil {
		return x.WorktreeRoot
	}
	return ""
}

func (x *UpRequest) GetExtras() map[string]string {
	if x != nil {
		return x.Extras
	}
	return nil
}

func (x *UpRequest) GetInitialDatabases() []string {
	if x != nil {
		return x.InitialDatabases
	}
	return nil
}

func (x *UpRequest) GetSocketDir() string {
	if x != nil {
		return x.SocketDir
	}
	return ""
}

// String error instead of gRPC status so plugins authored in non-Go
// languages can serialise a simple message without learning gRPC error
// codes. Empty string == success.
type UpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpResponse) Reset() {
	*x = UpResponse{}
	mi := &file_db_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpResponse) ProtoMessage() {}

func (x *UpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpResponse.ProtoReflect.Descriptor instead.
func (*UpResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{1}
}

func (x *UpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DownRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Port               int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	WorktreeRoot       string                 `protobuf:"bytes,2,opt,name=worktree_root,json=worktreeRoot,proto3" json:"worktree_root,omitempty"`
	GracefulTimeoutSec int32                  `protobuf:"varint,3,opt,name=graceful_timeout_sec,json=gracefulTimeoutSec,proto3" json:"graceful_timeout_sec,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownRequest) Reset() {
	*x = DownRequest{}
	mi := &file_db_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownRequest) ProtoMessage() {}

func (x *DownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownRequest.ProtoReflect.Descriptor instead.
func (*DownRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{2}
}

func (x *DownRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DownRequest) GetWorktreeRoot() string {
	if x != nil {
		return x.WorktreeRoot
	}
	return ""
}

func (x *DownRequest) GetGracefulTimeoutSec() int32 {
	if x != nil {
		return x.GracefulTimeoutSec
	}
	return 0
}

type DownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownResponse) Reset() {
	*x = DownResponse{}
	mi := &file_db_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownResponse) ProtoMessage() {}

func (x *DownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownResponse.ProtoReflect.Descriptor instead.
func (*DownResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{3}
}

func (x *DownResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadyCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Port          int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	TimeoutSec    int32                  `protobuf:"varint,2,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyCheckRequest) Reset() {
	*x = ReadyCheckRequest{}
	mi := &file_db_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyCheckRequest) ProtoMessage() {}

func (x *ReadyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyCheckRequest.ProtoReflect.Descriptor instead.
func (*ReadyCheckRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{4}
}

func (x *ReadyCheckRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ReadyCheckRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type ReadyCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyCheckResponse) Reset() {
	*x = ReadyCheckResponse{}
	mi := &file_db_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyCheckResponse) ProtoMessage() {}

func (x *ReadyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyCheckResponse.ProtoReflect.Descriptor instead.
func (*ReadyCheckResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{5}
}

func (x *ReadyCheckResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datadir       string                 `protobuf:"bytes,1,opt,name=datadir,proto3" json:"datadir,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupRequest) Reset() {
	*x = CleanupRequest{}
	mi := &file_db_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupRequest) ProtoMessage() {}

func (x *CleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupRequest.ProtoReflect.Descriptor instead.
func (*CleanupRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{6}
}

func (x *CleanupRequest) GetDatadir() string {
	if x != nil {
		return x.Datadir
	}
	return ""
}

func (x *CleanupRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type CleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupResponse) Reset() {
	*x = CleanupResponse{}
	mi := &file_db_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupResponse) ProtoMessage() {}

func (x *CleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupResponse.ProtoReflect.Descriptor instead.
func (*CleanupResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{7}
}

func (x *CleanupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PortRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           int32                  `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High          int32                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRangeResponse) Reset() {
	*x = PortRangeResponse{}
	mi := &file_db_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRangeResponse) ProtoMessage() {}

func (x *PortRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRangeResponse.ProtoReflect.Descriptor instead.
func (*PortRangeResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{8}
}

func (x *PortRangeResponse) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PortRangeResponse) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

type EnvVarsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Port             int32                  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	InitialDatabases []string               `protobuf:"bytes,2,rep,name=initial_databases,json=initialDatabases,proto3" json:"initial_databases,omitempty"`
	SocketDir        string                 `protobuf:"bytes,3,opt,name=socket_dir,json=socketDir,proto3" json:"socket_dir,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnvVarsRequest) Reset() {
	*x = EnvVarsRequest{}
	mi := &file_db_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVarsRequest) ProtoMessage() {}

func (x *EnvVarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVarsRequest.ProtoReflect.Descriptor instead.
func (*EnvVarsRequest) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{9}
}

func (x *EnvVarsRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *EnvVarsRequest) GetInitialDatabases() []string {
	if x != nil {
		return x.InitialDatabases
	}
	return nil
}

func (x *EnvVarsRequest) GetSocketDir() string {
	if x != nil {
		return x.SocketDir
	}
	return ""
}

type EnvVarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vars          map[string]string      `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVarsResponse) Reset() {
	*x = EnvVarsResponse{}
	mi := &file_db_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVarsResponse) ProtoMessage() {}

func (x *EnvVarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVarsResponse.ProtoReflect.Descriptor instead.
func (*EnvVarsResponse) Descriptor() ([]byte, []int) {
	return file_db_proto_rawDescGZIP(), []int{10}
}

func (x *EnvVarsResponse) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

var File_db_proto protoreflect.FileDescriptor

const file_db_proto_rawDesc = "" +
	"\n" +
	"\bdb.proto\x12\vbough.db.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xa1\x02\n" +
	"\tUpRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x18\n" +
	"\adatadir\x18\x02 \x01(\tR\adatadir\x12#\n" +
	"\rworktree_root\x18\x03 \x01(\tR\fworktreeRoot\x12:\n" +
	"\x06extras\x18\x04 \x03(\v2\".bough.db.v1.UpRequest.ExtrasEntryR\x06extras\x12+\n" +
	"\x11initial_databases\x18\x05 \x03(\tR\x10initialDatabases\x12\x1d\n" +
	"\n" +
	"socket_dir\x18\x06 \x01(\tR\tsocketDir\x1a9\n" +
	"\vExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	"\n" +
	"UpResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"x\n" +
	"\vDownRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12#\n" +
	"\rworktree_root\x18\x02 \x01(\tR\fworktreeRoot\x120\n" +
	"\x14graceful_timeout_sec\x18\x03 \x01(\x05R\x12gracefulTimeoutSec\"$\n" +
	"\fDownResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"H\n" +
	"\x11ReadyCheckRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12\x1f\n" +
	"\vtimeout_sec\x18\x02 \x01(\x05R\n" +
	"timeoutSec\"@\n" +
	"\x12ReadyCheckResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\">\n" +
	"\x0eCleanupRequest\x12\x18\n" +
	"\adatadir\x18\x01 \x01(\tR\adatadir\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"'\n" +
	"\x0fCleanupResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"9\n" +
	"\x11PortRangeResponse\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x05R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x05R\x04high\"p\n" +
	"\x0eEnvVarsRequest\x12\x12\n" +
	"\x04port\x18\x01 \x01(\x05R\x04port\x12+\n" +
	"\x11initial_databases\x18\x02 \x03(\tR\x10initialDatabases\x12\x1d\n" +
	"\n" +
	"socket_dir\x18\x03 \x01(\tR\tsocketDir\"\x86\x01\n" +
	"\x0fEnvVarsResponse\x12:\n" +
	"\x04vars\x18\x01 \x03(\v2&.bough.db.v1.EnvVarsResponse.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xa7\x03\n" +
	"\n" +
	"DBProvider\x125\n" +
	"\x02Up\x12\x16.bough.db.v1.UpRequest\x1a\x17.bough.db.v1.UpResponse\x12;\n" +
	"\x04Down\x12\x18.bough.db.v1.DownRequest\x1a\x19.bough.db.v1.DownResponse\x12M\n" +
	"\n" +
	"ReadyCheck\x12\x1e.bough.db.v1.ReadyCheckRequest\x1a\x1f.bough.db.v1.ReadyCheckResponse\x12D\n" +
	"\aCleanup\x12\x1b.bough.db.v1.CleanupRequest\x1a\x1c.bough.db.v1.CleanupResponse\x12J\n" +
	"\x10PortRangeDefault\x12\x16.google.protobuf.Empty\x1a\x1e.bough.db.v1.PortRangeResponse\x12D\n" +
	"\aEnvVars\x12\x1b.bough.db.v1.EnvVarsRequest\x1a\x1c.bough.db.v1.EnvVarsResponseB7Z5github.com/ikeikeikeike/bough/plugins/db/api/proto;pbb\x06proto3"

var (
	file_db_proto_rawDescOnce sync.Once
	file_db_proto_rawDescData []byte
)

func file_db_proto_rawDescGZIP() []byte {
	file_db_proto_rawDescOnce.Do(func() {
		file_db_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)))
	})
	return file_db_proto_rawDescData
}

var file_db_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_db_proto_goTypes = []any{
	(*UpRequest)(nil),          // 0: bough.db.v1.UpRequest
	(*UpResponse)(nil),         // 1: bough.db.v1.UpResponse
	(*DownRequest)(nil),        // 2: bough.db.v1.DownRequest
	(*DownResponse)(nil),       // 3: bough.db.v1.DownResponse
	(*ReadyCheckRequest)(nil),  // 4: bough.db.v1.ReadyCheckRequest
	(*ReadyCheckResponse)(nil), // 5: bough.db.v1.ReadyCheckResponse
	(*CleanupRequest)(nil),     // 6: bough.db.v1.CleanupRequest
	(*CleanupResponse)(nil),    // 7: bough.db.v1.CleanupResponse
	(*PortRangeResponse)(nil),  // 8: bough.db.v1.PortRangeResponse
	(*EnvVarsRequest)(nil),     // 9: bough.db.v1.EnvVarsRequest
	(*EnvVarsResponse)(nil),    // 10: bough.db.v1.EnvVarsResponse
	nil,                        // 11: bough.db.v1.UpRequest.ExtrasEntry
	nil,                        // 12: bough.db.v1.EnvVarsResponse.VarsEntry
	(*emptypb.Empty)(nil),      // 13: google.protobuf.Empty
}
var file_db_proto_depIdxs = []int32{
	11, // 0: bough.db.v1.UpRequest.extras:type_name -> bough.db.v1.UpRequest.ExtrasEntry
	12, // 1: bough.db.v1.EnvVarsResponse.vars:type_name -> bough.db.v1.EnvVarsResponse.VarsEntry
	0,  // 2: bough.db.v1.DBProvider.Up:input_type -> bough.db.v1.UpRequest
	2,  // 3: bough.db.v1.DBProvider.Down:input_type -> bough.db.v1.DownRequest
	4,  // 4: bough.db.v1.DBProvider.ReadyCheck:input_type -> bough.db.v1.ReadyCheckRequest
	6,  // 5: bough.db.v1.DBProvider.Cleanup:input_type -> bough.db.v1.CleanupRequest
	13, // 6: bough.db.v1.DBProvider.PortRangeDefault:input_type -> google.protobuf.Empty
	9,  // 7: bough.db.v1.DBProvider.EnvVars:input_type -> bough.db.v1.EnvVarsRequest
	1,  // 8: bough.db.v1.DBProvider.Up:output_type -> bough.db.v1.UpResponse
	3,  // 9: bough.db.v1.DBProvider.Down:output_type -> bough.db.v1.DownResponse
	5,  // 10: bough.db.v1.DBProvider.ReadyCheck:output_type -> bough.db.v1.ReadyCheckResponse
	7,  // 11: bough.db.v1.DBProvider.Cleanup:output_type -> bough.db.v1.CleanupResponse
	8,  // 12: bough.db.v1.DBProvider.PortRangeDefault:output_type -> bough.db.v1.PortRangeResponse
	10, // 13: bough.db.v1.DBProvider.EnvVars:output_type -> bough.db.v1.EnvVarsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_db_proto_init() }
func file_db_proto_init() {
	if File_db_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_proto_rawDesc), len(file_db_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_proto_goTypes,
		DependencyIndexes: file_db_proto_depIdxs,
		MessageInfos:      file_db_proto_msgTypes,
	}.Build()
	File_db_proto = out.File
	file_db_proto_goTypes = nil
	file_db_proto_depIdxs = nil
}
