// db.proto is the contract between the bough host and any
// `bough-plugin-<kind>` binary that provisions a per-worktree database.
// Plugins implement DBProvider over Hashicorp go-plugin's gRPC transport.
//
// Versioning: bumping ProtocolVersion in plugins/db/api/handshake.go is
// what gates a backwards-incompatible change here. Add new fields with
// new tag numbers, do not renumber existing ones.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: db.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DBProvider_Up_FullMethodName               = "/bough.db.v1.DBProvider/Up"
	DBProvider_Down_FullMethodName             = "/bough.db.v1.DBProvider/Down"
	DBProvider_ReadyCheck_FullMethodName       = "/bough.db.v1.DBProvider/ReadyCheck"
	DBProvider_Cleanup_FullMethodName          = "/bough.db.v1.DBProvider/Cleanup"
	DBProvider_PortRangeDefault_FullMethodName = "/bough.db.v1.DBProvider/PortRangeDefault"
	DBProvider_EnvVars_FullMethodName          = "/bough.db.v1.DBProvider/EnvVars"
)

// DBProviderClient is the client API for DBProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DBProvider is the lifecycle of one per-worktree database instance.
type DBProviderClient interface {
	// Up starts the database listening on `port`, with its data directory
	// anchored at `datadir`. The host passes `worktree_root` so the plugin
	// can resolve a `nix run` invocation against the embedded flake without
	// needing global state.
	Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpResponse, error)
	// Down asks the plugin to gracefully stop the instance and clean up
	// any supervisor processes it spawned.
	Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (*DownResponse, error)
	// ReadyCheck polls for `timeout_sec` seconds until the instance accepts
	// connections on `port`, returning ready=true on success.
	ReadyCheck(ctx context.Context, in *ReadyCheckRequest, opts ...grpc.CallOption) (*ReadyCheckResponse, error)
	// Cleanup removes the on-disk data directory after Down has confirmed
	// the instance is no longer running.
	Cleanup(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error)
	// PortRangeDefault returns the [low, high] port range the plugin
	// recommends, used when the YAML does not override `port_range`.
	PortRangeDefault(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PortRangeResponse, error)
	// EnvVars returns the set of environment variables consumers (the host
	// and any sibling repo) should see in their rendered .env.local for
	// this database. The keys typically include host / port / socket /
	// initial database names.
	EnvVars(ctx context.Context, in *EnvVarsRequest, opts ...grpc.CallOption) (*EnvVarsResponse, error)
}

type dBProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewDBProviderClient(cc grpc.ClientConnInterface) DBProviderClient {
	return &dBProviderClient{cc}
}

func (c *dBProviderClient) Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpResponse)
	err := c.cc.Invoke(ctx, DBProvider_Up_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProviderClient) Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (*DownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownResponse)
	err := c.cc.Invoke(ctx, DBProvider_Down_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProviderClient) ReadyCheck(ctx context.Context, in *ReadyCheckRequest, opts ...grpc.CallOption) (*ReadyCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyCheckResponse)
	err := c.cc.Invoke(ctx, DBProvider_ReadyCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProviderClient) Cleanup(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupResponse)
	err := c.cc.Invoke(ctx, DBProvider_Cleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProviderClient) PortRangeDefault(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PortRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortRangeResponse)
	err := c.cc.Invoke(ctx, DBProvider_PortRangeDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBProviderClient) EnvVars(ctx context.Context, in *EnvVarsRequest, opts ...grpc.CallOption) (*EnvVarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvVarsResponse)
	err := c.cc.Invoke(ctx, DBProvider_EnvVars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBProviderServer is the server API for DBProvider service.
// All implementations must embed UnimplementedDBProviderServer
// for forward compatibility.
//
// DBProvider is the lifecycle of one per-worktree database instance.
type DBProviderServer interface {
	// Up starts the database listening on `port`, with its data directory
	// anchored at `datadir`. The host passes `worktree_root` so the plugin
	// can resolve a `nix run` invocation against the embedded flake without
	// needing global state.
	Up(context.Context, *UpRequest) (*UpResponse, error)
	// Down asks the plugin to gracefully stop the instance and clean up
	// any supervisor processes it spawned.
	Down(context.Context, *DownRequest) (*DownResponse, error)
	// ReadyCheck polls for `timeout_sec` seconds until the instance accepts
	// connections on `port`, returning ready=true on success.
	ReadyCheck(context.Context, *ReadyCheckRequest) (*ReadyCheckResponse, error)
	// Cleanup removes the on-disk data directory after Down has confirmed
	// the instance is no longer running.
	Cleanup(context.Context, *CleanupRequest) (*CleanupResponse, error)
	// PortRangeDefault returns the [low, high] port range the plugin
	// recommends, used when the YAML does not override `port_range`.
	PortRangeDefault(context.Context, *emptypb.Empty) (*PortRangeResponse, error)
	// EnvVars returns the set of environment variables consumers (the host
	// and any sibling repo) should see in their rendered .env.local for
	// this database. The keys typically include host / port / socket /
	// initial database names.
	EnvVars(context.Context, *EnvVarsRequest) (*EnvVarsResponse, error)
	mustEmbedUnimplementedDBProviderServer()
}

// UnimplementedDBProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDBProviderServer struct{}

func (UnimplementedDBProviderServer) Up(context.Context, *UpRequest) (*UpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Up not implemented")
}
func (UnimplementedDBProviderServer) Down(context.Context, *DownRequest) (*DownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Down not implemented")
}
func (UnimplementedDBProviderServer) ReadyCheck(context.Context, *ReadyCheckRequest) (*ReadyCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadyCheck not implemented")
}
func (UnimplementedDBProviderServer) Cleanup(context.Context, *CleanupRequest) (*CleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cleanup not implemented")
}
func (UnimplementedDBProviderServer) PortRangeDefault(context.Context, *emptypb.Empty) (*PortRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PortRangeDefault not implemented")
}
func (UnimplementedDBProviderServer) EnvVars(context.Context, *EnvVarsRequest) (*EnvVarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnvVars not implemented")
}
func (UnimplementedDBProviderServer) mustEmbedUnimplementedDBProviderServer() {}
func (UnimplementedDBProviderServer) testEmbeddedByValue()                    {}

// UnsafeDBProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBProviderServer will
// result in compilation errors.
type UnsafeDBProviderServer interface {
	mustEmbedUnimplementedDBProviderServer()
}

func RegisterDBProviderServer(s grpc.ServiceRegistrar, srv DBProviderServer) {
	// If the following call panics, it indicates UnimplementedDBProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DBProvider_ServiceDesc, srv)
}

func _DBProvider_Up_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProviderServer).Up(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBProvider_Up_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProviderServer).Up(ctx, req.(*UpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProvider_Down_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProviderServer).Down(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBProvider_Down_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProviderServer).Down(ctx, req.(*DownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProvider_ReadyCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProviderServer).ReadyCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBProvider_ReadyCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProviderServer).ReadyCheck(ctx, req.(*ReadyCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProvider_Cleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProviderServer).Cleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBProvider_Cleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProviderServer).Cleanup(ctx, req.(*CleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProvider_PortRangeDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProviderServer).PortRangeDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBProvider_PortRangeDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProviderServer).PortRangeDefault(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _DBProvider_EnvVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvVarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBProviderServer).EnvVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DBProvider_EnvVars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBProviderServer).EnvVars(ctx, req.(*EnvVarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DBProvider_ServiceDesc is the grpc.ServiceDesc for DBProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bough.db.v1.DBProvider",
	HandlerType: (*DBProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Up",
			Handler:    _DBProvider_Up_Handler,
		},
		{
			MethodName: "Down",
			Handler:    _DBProvider_Down_Handler,
		},
		{
			MethodName: "ReadyCheck",
			Handler:    _DBProvider_ReadyCheck_Handler,
		},
		{
			MethodName: "Cleanup",
			Handler:    _DBProvider_Cleanup_Handler,
		},
		{
			MethodName: "PortRangeDefault",
			Handler:    _DBProvider_PortRangeDefault_Handler,
		},
		{
			MethodName: "EnvVars",
			Handler:    _DBProvider_EnvVars_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}
