// capability.proto freezes the v0.5.0 wire contract for
// `bough-plugin-capability-<name>` plugins WITHOUT shipping a working
// implementation. v0.5 only generates the gRPC stubs and the Go
// interface; the host's `bough capability compile` CLI lands in
// v0.6.0 along with the first official compilers (SkillX adapter,
// Anything2Skill adapter, Alita-G adapter — all v0.6.x experimental
// status, none ship as core artifacts).
//
// Why freeze in v0.5 if we will not implement until v0.6:
//   1. plugin authors can start prototyping against a stable contract
//      while v0.5 is shipping.
//   2. pkg/schema/CapabilityArtifact is committed in v0.5 too, so
//      the Go-side data structures and the wire format land together.
//   3. v0.5 docs (CAPABILITY_COMPILER_PREVIEW.md) can show concrete
//      message shapes rather than vapourware diagrams.
//
// The CapabilityArtifact message intentionally carries minimum-viable
// fields (Kind, Name, Description, InvocationCondition, Inputs,
// Outputs, Steps, Constraints, EvidenceRefs, Confidence, Version,
// SourceInstinctIDs) plus a Payload byte slot for plugin-defined
// metadata. v0.6 adds richer provenance (target_format, target_host,
// validation probes, supply-chain tree_sha) — those land as new
// optional fields on the same message, never as a breaking change to
// the v0.5 wire shape. See docs/CAPABILITY_COMPILER_PREVIEW.md and
// docs/SECURITY.md (SKILL.md supply-chain attack surface).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: capability.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CapabilityCompiler_Compile_FullMethodName = "/bough.capability.v1.CapabilityCompiler/Compile"
)

// CapabilityCompilerClient is the client API for CapabilityCompiler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CapabilityCompiler turns an approved set of InstinctCandidates
// (referenced by ID; the host owns lookup) into one or more
// CapabilityArtifacts that can be exported in v0.6+ as Claude Skills,
// Agent Skills, MCP tools/resources/prompts, raw markdown, or JSON.
type CapabilityCompilerClient interface {
	// Compile is the only RPC. The host passes the candidates' IDs and
	// the desired target_kinds; the plugin synthesises matching
	// artifacts. DryRun=true asks the plugin to return the artifacts
	// without committing any side effects (relevant when a future
	// compiler runs an LLM with non-zero spend per invocation).
	Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error)
}

type capabilityCompilerClient struct {
	cc grpc.ClientConnInterface
}

func NewCapabilityCompilerClient(cc grpc.ClientConnInterface) CapabilityCompilerClient {
	return &capabilityCompilerClient{cc}
}

func (c *capabilityCompilerClient) Compile(ctx context.Context, in *CompileRequest, opts ...grpc.CallOption) (*CompileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompileResponse)
	err := c.cc.Invoke(ctx, CapabilityCompiler_Compile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CapabilityCompilerServer is the server API for CapabilityCompiler service.
// All implementations must embed UnimplementedCapabilityCompilerServer
// for forward compatibility.
//
// CapabilityCompiler turns an approved set of InstinctCandidates
// (referenced by ID; the host owns lookup) into one or more
// CapabilityArtifacts that can be exported in v0.6+ as Claude Skills,
// Agent Skills, MCP tools/resources/prompts, raw markdown, or JSON.
type CapabilityCompilerServer interface {
	// Compile is the only RPC. The host passes the candidates' IDs and
	// the desired target_kinds; the plugin synthesises matching
	// artifacts. DryRun=true asks the plugin to return the artifacts
	// without committing any side effects (relevant when a future
	// compiler runs an LLM with non-zero spend per invocation).
	Compile(context.Context, *CompileRequest) (*CompileResponse, error)
	mustEmbedUnimplementedCapabilityCompilerServer()
}

// UnimplementedCapabilityCompilerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCapabilityCompilerServer struct{}

func (UnimplementedCapabilityCompilerServer) Compile(context.Context, *CompileRequest) (*CompileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Compile not implemented")
}
func (UnimplementedCapabilityCompilerServer) mustEmbedUnimplementedCapabilityCompilerServer() {}
func (UnimplementedCapabilityCompilerServer) testEmbeddedByValue()                            {}

// UnsafeCapabilityCompilerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CapabilityCompilerServer will
// result in compilation errors.
type UnsafeCapabilityCompilerServer interface {
	mustEmbedUnimplementedCapabilityCompilerServer()
}

func RegisterCapabilityCompilerServer(s grpc.ServiceRegistrar, srv CapabilityCompilerServer) {
	// If the following call panics, it indicates UnimplementedCapabilityCompilerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CapabilityCompiler_ServiceDesc, srv)
}

func _CapabilityCompiler_Compile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CapabilityCompilerServer).Compile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CapabilityCompiler_Compile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CapabilityCompilerServer).Compile(ctx, req.(*CompileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CapabilityCompiler_ServiceDesc is the grpc.ServiceDesc for CapabilityCompiler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CapabilityCompiler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bough.capability.v1.CapabilityCompiler",
	HandlerType: (*CapabilityCompilerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Compile",
			Handler:    _CapabilityCompiler_Compile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "capability.proto",
}
