// capability.proto freezes the v0.5.0 wire contract for
// `bough-plugin-capability-<name>` plugins WITHOUT shipping a working
// implementation. v0.5 only generates the gRPC stubs and the Go
// interface; the host's `bough capability compile` CLI lands in
// v0.6.0 along with the first official compilers (SkillX adapter,
// Anything2Skill adapter, Alita-G adapter — all v0.6.x experimental
// status, none ship as core artifacts).
//
// Why freeze in v0.5 if we will not implement until v0.6:
//   1. plugin authors can start prototyping against a stable contract
//      while v0.5 is shipping.
//   2. pkg/schema/CapabilityArtifact is committed in v0.5 too, so
//      the Go-side data structures and the wire format land together.
//   3. v0.5 docs (CAPABILITY_COMPILER_PREVIEW.md) can show concrete
//      message shapes rather than vapourware diagrams.
//
// The CapabilityArtifact message intentionally carries minimum-viable
// fields (Kind, Name, Description, InvocationCondition, Inputs,
// Outputs, Steps, Constraints, EvidenceRefs, Confidence, Version,
// SourceInstinctIDs) plus a Payload byte slot for plugin-defined
// metadata. v0.6 adds richer provenance (target_format, target_host,
// validation probes, supply-chain tree_sha) — those land as new
// optional fields on the same message, never as a breaking change to
// the v0.5 wire shape. See docs/CAPABILITY_COMPILER_PREVIEW.md and
// docs/SECURITY.md (SKILL.md supply-chain attack surface).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: capability.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CapabilityArtifactKind enumerates the eight derivation targets the
// bough vision (post round 2.5 / round 3) treats as first-class. v0.5
// only persists artifacts of these kinds; the compiler is not asked
// to invent new kinds.
type CapabilityArtifactKind int32

const (
	CapabilityArtifactKind_ARTIFACT_KIND_UNSPECIFIED CapabilityArtifactKind = 0
	CapabilityArtifactKind_ARTIFACT_KIND_MEMORY      CapabilityArtifactKind = 1
	CapabilityArtifactKind_ARTIFACT_KIND_RULE        CapabilityArtifactKind = 2
	CapabilityArtifactKind_ARTIFACT_KIND_SKILL       CapabilityArtifactKind = 3
	CapabilityArtifactKind_ARTIFACT_KIND_COMMAND     CapabilityArtifactKind = 4
	CapabilityArtifactKind_ARTIFACT_KIND_WORKFLOW    CapabilityArtifactKind = 5
	CapabilityArtifactKind_ARTIFACT_KIND_TOOL        CapabilityArtifactKind = 6
	CapabilityArtifactKind_ARTIFACT_KIND_AGENT       CapabilityArtifactKind = 7
	CapabilityArtifactKind_ARTIFACT_KIND_EVALUATOR   CapabilityArtifactKind = 8
)

// Enum value maps for CapabilityArtifactKind.
var (
	CapabilityArtifactKind_name = map[int32]string{
		0: "ARTIFACT_KIND_UNSPECIFIED",
		1: "ARTIFACT_KIND_MEMORY",
		2: "ARTIFACT_KIND_RULE",
		3: "ARTIFACT_KIND_SKILL",
		4: "ARTIFACT_KIND_COMMAND",
		5: "ARTIFACT_KIND_WORKFLOW",
		6: "ARTIFACT_KIND_TOOL",
		7: "ARTIFACT_KIND_AGENT",
		8: "ARTIFACT_KIND_EVALUATOR",
	}
	CapabilityArtifactKind_value = map[string]int32{
		"ARTIFACT_KIND_UNSPECIFIED": 0,
		"ARTIFACT_KIND_MEMORY":      1,
		"ARTIFACT_KIND_RULE":        2,
		"ARTIFACT_KIND_SKILL":       3,
		"ARTIFACT_KIND_COMMAND":     4,
		"ARTIFACT_KIND_WORKFLOW":    5,
		"ARTIFACT_KIND_TOOL":        6,
		"ARTIFACT_KIND_AGENT":       7,
		"ARTIFACT_KIND_EVALUATOR":   8,
	}
)

func (x CapabilityArtifactKind) Enum() *CapabilityArtifactKind {
	p := new(CapabilityArtifactKind)
	*p = x
	return p
}

func (x CapabilityArtifactKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CapabilityArtifactKind) Descriptor() protoreflect.EnumDescriptor {
	return file_capability_proto_enumTypes[0].Descriptor()
}

func (CapabilityArtifactKind) Type() protoreflect.EnumType {
	return &file_capability_proto_enumTypes[0]
}

func (x CapabilityArtifactKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CapabilityArtifactKind.Descriptor instead.
func (CapabilityArtifactKind) EnumDescriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{0}
}

// Stability mirrors pkg/schema.Stability. v0.5 ships the
// CapabilityArtifact schema as EXPERIMENTAL so consumers know the
// shape may grow optional fields in v0.6 without a wire break.
type Stability int32

const (
	Stability_STABILITY_UNSPECIFIED  Stability = 0
	Stability_STABILITY_STABLE       Stability = 1
	Stability_STABILITY_PREVIEW      Stability = 2
	Stability_STABILITY_EXPERIMENTAL Stability = 3
)

// Enum value maps for Stability.
var (
	Stability_name = map[int32]string{
		0: "STABILITY_UNSPECIFIED",
		1: "STABILITY_STABLE",
		2: "STABILITY_PREVIEW",
		3: "STABILITY_EXPERIMENTAL",
	}
	Stability_value = map[string]int32{
		"STABILITY_UNSPECIFIED":  0,
		"STABILITY_STABLE":       1,
		"STABILITY_PREVIEW":      2,
		"STABILITY_EXPERIMENTAL": 3,
	}
)

func (x Stability) Enum() *Stability {
	p := new(Stability)
	*p = x
	return p
}

func (x Stability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Stability) Descriptor() protoreflect.EnumDescriptor {
	return file_capability_proto_enumTypes[1].Descriptor()
}

func (Stability) Type() protoreflect.EnumType {
	return &file_capability_proto_enumTypes[1]
}

func (x Stability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Stability.Descriptor instead.
func (Stability) EnumDescriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{1}
}

type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	WorktreeId    string                 `protobuf:"bytes,2,opt,name=worktree_id,json=worktreeId,proto3" json:"worktree_id,omitempty"`
	RepoName      string                 `protobuf:"bytes,3,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_capability_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Scope) GetWorktreeId() string {
	if x != nil {
		return x.WorktreeId
	}
	return ""
}

func (x *Scope) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

// CapabilityArtifact is the compiled output. Payload is a free-form
// JSON byte slot so v0.6+ compilers (Anything2Skill, gh skill format,
// MCP tools/resources/prompts) can carry their richer metadata
// without needing a wire bump. The host treats Payload as opaque on
// v0.5 — it is round-tripped through Export/Import but not parsed.
type CapabilityArtifact struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Stability           Stability              `protobuf:"varint,1,opt,name=stability,proto3,enum=bough.capability.v1.Stability" json:"stability,omitempty"`
	Id                  string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Kind                CapabilityArtifactKind `protobuf:"varint,3,opt,name=kind,proto3,enum=bough.capability.v1.CapabilityArtifactKind" json:"kind,omitempty"`
	Name                string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	InvocationCondition string                 `protobuf:"bytes,6,opt,name=invocation_condition,json=invocationCondition,proto3" json:"invocation_condition,omitempty"`
	Inputs              []string               `protobuf:"bytes,7,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Outputs             []string               `protobuf:"bytes,8,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Steps               []string               `protobuf:"bytes,9,rep,name=steps,proto3" json:"steps,omitempty"`
	Constraints         []string               `protobuf:"bytes,10,rep,name=constraints,proto3" json:"constraints,omitempty"`
	EvidenceRefs        []string               `protobuf:"bytes,11,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	Confidence          float64                `protobuf:"fixed64,12,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Version             string                 `protobuf:"bytes,13,opt,name=version,proto3" json:"version,omitempty"`
	SourceInstincts     []string               `protobuf:"bytes,14,rep,name=source_instincts,json=sourceInstincts,proto3" json:"source_instincts,omitempty"`
	Scope               *Scope                 `protobuf:"bytes,15,opt,name=scope,proto3" json:"scope,omitempty"`
	CreatedAt           int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Payload             []byte                 `protobuf:"bytes,17,opt,name=payload,proto3" json:"payload,omitempty"` // free-form JSON, plugin-defined
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CapabilityArtifact) Reset() {
	*x = CapabilityArtifact{}
	mi := &file_capability_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilityArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilityArtifact) ProtoMessage() {}

func (x *CapabilityArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilityArtifact.ProtoReflect.Descriptor instead.
func (*CapabilityArtifact) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilityArtifact) GetStability() Stability {
	if x != nil {
		return x.Stability
	}
	return Stability_STABILITY_UNSPECIFIED
}

func (x *CapabilityArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CapabilityArtifact) GetKind() CapabilityArtifactKind {
	if x != nil {
		return x.Kind
	}
	return CapabilityArtifactKind_ARTIFACT_KIND_UNSPECIFIED
}

func (x *CapabilityArtifact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CapabilityArtifact) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CapabilityArtifact) GetInvocationCondition() string {
	if x != nil {
		return x.InvocationCondition
	}
	return ""
}

func (x *CapabilityArtifact) GetInputs() []string {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *CapabilityArtifact) GetOutputs() []string {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *CapabilityArtifact) GetSteps() []string {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *CapabilityArtifact) GetConstraints() []string {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *CapabilityArtifact) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *CapabilityArtifact) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *CapabilityArtifact) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CapabilityArtifact) GetSourceInstincts() []string {
	if x != nil {
		return x.SourceInstincts
	}
	return nil
}

func (x *CapabilityArtifact) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CapabilityArtifact) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *CapabilityArtifact) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// EvidencePolicy gates how aggressive a compiler is allowed to be.
// require_min_traces=3 keeps single-shot anecdotes from being
// promoted; allowed_sources whitelists which trace sources count
// toward the minimum.
type EvidencePolicy struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequireMinTraces int32                  `protobuf:"varint,1,opt,name=require_min_traces,json=requireMinTraces,proto3" json:"require_min_traces,omitempty"`
	AllowedSources   []string               `protobuf:"bytes,2,rep,name=allowed_sources,json=allowedSources,proto3" json:"allowed_sources,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EvidencePolicy) Reset() {
	*x = EvidencePolicy{}
	mi := &file_capability_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvidencePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvidencePolicy) ProtoMessage() {}

func (x *EvidencePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvidencePolicy.ProtoReflect.Descriptor instead.
func (*EvidencePolicy) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{2}
}

func (x *EvidencePolicy) GetRequireMinTraces() int32 {
	if x != nil {
		return x.RequireMinTraces
	}
	return 0
}

func (x *EvidencePolicy) GetAllowedSources() []string {
	if x != nil {
		return x.AllowedSources
	}
	return nil
}

type CompileRequest struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	SourceInstinctIds []string                 `protobuf:"bytes,1,rep,name=source_instinct_ids,json=sourceInstinctIds,proto3" json:"source_instinct_ids,omitempty"`
	TargetKinds       []CapabilityArtifactKind `protobuf:"varint,2,rep,packed,name=target_kinds,json=targetKinds,proto3,enum=bough.capability.v1.CapabilityArtifactKind" json:"target_kinds,omitempty"`
	Scope             *Scope                   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	EvidencePolicy    *EvidencePolicy          `protobuf:"bytes,4,opt,name=evidence_policy,json=evidencePolicy,proto3" json:"evidence_policy,omitempty"`
	RequireApproval   bool                     `protobuf:"varint,5,opt,name=require_approval,json=requireApproval,proto3" json:"require_approval,omitempty"`
	DryRun            bool                     `protobuf:"varint,6,opt,name=dry_run,json=dryRun,proto3" json:"dry_run,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompileRequest) Reset() {
	*x = CompileRequest{}
	mi := &file_capability_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileRequest) ProtoMessage() {}

func (x *CompileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileRequest.ProtoReflect.Descriptor instead.
func (*CompileRequest) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{3}
}

func (x *CompileRequest) GetSourceInstinctIds() []string {
	if x != nil {
		return x.SourceInstinctIds
	}
	return nil
}

func (x *CompileRequest) GetTargetKinds() []CapabilityArtifactKind {
	if x != nil {
		return x.TargetKinds
	}
	return nil
}

func (x *CompileRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *CompileRequest) GetEvidencePolicy() *EvidencePolicy {
	if x != nil {
		return x.EvidencePolicy
	}
	return nil
}

func (x *CompileRequest) GetRequireApproval() bool {
	if x != nil {
		return x.RequireApproval
	}
	return false
}

func (x *CompileRequest) GetDryRun() bool {
	if x != nil {
		return x.DryRun
	}
	return false
}

type CompileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Candidates    []*CapabilityArtifact  `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompileResponse) Reset() {
	*x = CompileResponse{}
	mi := &file_capability_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompileResponse) ProtoMessage() {}

func (x *CompileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capability_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompileResponse.ProtoReflect.Descriptor instead.
func (*CompileResponse) Descriptor() ([]byte, []int) {
	return file_capability_proto_rawDescGZIP(), []int{4}
}

func (x *CompileResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CompileResponse) GetCandidates() []*CapabilityArtifact {
	if x != nil {
		return x.Candidates
	}
	return nil
}

var File_capability_proto protoreflect.FileDescriptor

const file_capability_proto_rawDesc = "" +
	"\n" +
	"\x10capability.proto\x12\x13bough.capability.v1\"[\n" +
	"\x05Scope\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1f\n" +
	"\vworktree_id\x18\x02 \x01(\tR\n" +
	"worktreeId\x12\x1b\n" +
	"\trepo_name\x18\x03 \x01(\tR\brepoName\"\xeb\x04\n" +
	"\x12CapabilityArtifact\x12<\n" +
	"\tstability\x18\x01 \x01(\x0e2\x1e.bough.capability.v1.StabilityR\tstability\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12?\n" +
	"\x04kind\x18\x03 \x01(\x0e2+.bough.capability.v1.CapabilityArtifactKindR\x04kind\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x121\n" +
	"\x14invocation_condition\x18\x06 \x01(\tR\x13invocationCondition\x12\x16\n" +
	"\x06inputs\x18\a \x03(\tR\x06inputs\x12\x18\n" +
	"\aoutputs\x18\b \x03(\tR\aoutputs\x12\x14\n" +
	"\x05steps\x18\t \x03(\tR\x05steps\x12 \n" +
	"\vconstraints\x18\n" +
	" \x03(\tR\vconstraints\x12#\n" +
	"\revidence_refs\x18\v \x03(\tR\fevidenceRefs\x12\x1e\n" +
	"\n" +
	"confidence\x18\f \x01(\x01R\n" +
	"confidence\x12\x18\n" +
	"\aversion\x18\r \x01(\tR\aversion\x12)\n" +
	"\x10source_instincts\x18\x0e \x03(\tR\x0fsourceInstincts\x120\n" +
	"\x05scope\x18\x0f \x01(\v2\x1a.bough.capability.v1.ScopeR\x05scope\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x12\x18\n" +
	"\apayload\x18\x11 \x01(\fR\apayload\"g\n" +
	"\x0eEvidencePolicy\x12,\n" +
	"\x12require_min_traces\x18\x01 \x01(\x05R\x10requireMinTraces\x12'\n" +
	"\x0fallowed_sources\x18\x02 \x03(\tR\x0eallowedSources\"\xd4\x02\n" +
	"\x0eCompileRequest\x12.\n" +
	"\x13source_instinct_ids\x18\x01 \x03(\tR\x11sourceInstinctIds\x12N\n" +
	"\ftarget_kinds\x18\x02 \x03(\x0e2+.bough.capability.v1.CapabilityArtifactKindR\vtargetKinds\x120\n" +
	"\x05scope\x18\x03 \x01(\v2\x1a.bough.capability.v1.ScopeR\x05scope\x12L\n" +
	"\x0fevidence_policy\x18\x04 \x01(\v2#.bough.capability.v1.EvidencePolicyR\x0eevidencePolicy\x12)\n" +
	"\x10require_approval\x18\x05 \x01(\bR\x0frequireApproval\x12\x17\n" +
	"\adry_run\x18\x06 \x01(\bR\x06dryRun\"p\n" +
	"\x0fCompileResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12G\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2'.bough.capability.v1.CapabilityArtifactR\n" +
	"candidates*\x87\x02\n" +
	"\x16CapabilityArtifactKind\x12\x1d\n" +
	"\x19ARTIFACT_KIND_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ARTIFACT_KIND_MEMORY\x10\x01\x12\x16\n" +
	"\x12ARTIFACT_KIND_RULE\x10\x02\x12\x17\n" +
	"\x13ARTIFACT_KIND_SKILL\x10\x03\x12\x19\n" +
	"\x15ARTIFACT_KIND_COMMAND\x10\x04\x12\x1a\n" +
	"\x16ARTIFACT_KIND_WORKFLOW\x10\x05\x12\x16\n" +
	"\x12ARTIFACT_KIND_TOOL\x10\x06\x12\x17\n" +
	"\x13ARTIFACT_KIND_AGENT\x10\a\x12\x1b\n" +
	"\x17ARTIFACT_KIND_EVALUATOR\x10\b*o\n" +
	"\tStability\x12\x19\n" +
	"\x15STABILITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10STABILITY_STABLE\x10\x01\x12\x15\n" +
	"\x11STABILITY_PREVIEW\x10\x02\x12\x1a\n" +
	"\x16STABILITY_EXPERIMENTAL\x10\x032j\n" +
	"\x12CapabilityCompiler\x12T\n" +
	"\aCompile\x12#.bough.capability.v1.CompileRequest\x1a$.bough.capability.v1.CompileResponseB?Z=github.com/ikeikeikeike/bough/plugins/capability/api/proto;pbb\x06proto3"

var (
	file_capability_proto_rawDescOnce sync.Once
	file_capability_proto_rawDescData []byte
)

func file_capability_proto_rawDescGZIP() []byte {
	file_capability_proto_rawDescOnce.Do(func() {
		file_capability_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capability_proto_rawDesc), len(file_capability_proto_rawDesc)))
	})
	return file_capability_proto_rawDescData
}

var file_capability_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_capability_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_capability_proto_goTypes = []any{
	(CapabilityArtifactKind)(0), // 0: bough.capability.v1.CapabilityArtifactKind
	(Stability)(0),              // 1: bough.capability.v1.Stability
	(*Scope)(nil),               // 2: bough.capability.v1.Scope
	(*CapabilityArtifact)(nil),  // 3: bough.capability.v1.CapabilityArtifact
	(*EvidencePolicy)(nil),      // 4: bough.capability.v1.EvidencePolicy
	(*CompileRequest)(nil),      // 5: bough.capability.v1.CompileRequest
	(*CompileResponse)(nil),     // 6: bough.capability.v1.CompileResponse
}
var file_capability_proto_depIdxs = []int32{
	1, // 0: bough.capability.v1.CapabilityArtifact.stability:type_name -> bough.capability.v1.Stability
	0, // 1: bough.capability.v1.CapabilityArtifact.kind:type_name -> bough.capability.v1.CapabilityArtifactKind
	2, // 2: bough.capability.v1.CapabilityArtifact.scope:type_name -> bough.capability.v1.Scope
	0, // 3: bough.capability.v1.CompileRequest.target_kinds:type_name -> bough.capability.v1.CapabilityArtifactKind
	2, // 4: bough.capability.v1.CompileRequest.scope:type_name -> bough.capability.v1.Scope
	4, // 5: bough.capability.v1.CompileRequest.evidence_policy:type_name -> bough.capability.v1.EvidencePolicy
	3, // 6: bough.capability.v1.CompileResponse.candidates:type_name -> bough.capability.v1.CapabilityArtifact
	5, // 7: bough.capability.v1.CapabilityCompiler.Compile:input_type -> bough.capability.v1.CompileRequest
	6, // 8: bough.capability.v1.CapabilityCompiler.Compile:output_type -> bough.capability.v1.CompileResponse
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_capability_proto_init() }
func file_capability_proto_init() {
	if File_capability_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capability_proto_rawDesc), len(file_capability_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_capability_proto_goTypes,
		DependencyIndexes: file_capability_proto_depIdxs,
		EnumInfos:         file_capability_proto_enumTypes,
		MessageInfos:      file_capability_proto_msgTypes,
	}.Build()
	File_capability_proto = out.File
	file_capability_proto_goTypes = nil
	file_capability_proto_depIdxs = nil
}
