package cli

import (
	"bytes"
	"context"
	"errors"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/ikeikeikeike/bough/internal/config"
)

// TestParseEnvLocal_BasicKV is the floor: a single `KEY=VALUE` line
// with no surprises should round-trip verbatim.
func TestParseEnvLocal_BasicKV(t *testing.T) {
	path := writeEnvFile(t, "FOO=bar\n")
	got := parseEnvLocal(io.Discard, "demo", path)
	if len(got) != 1 || got[0] != "FOO=bar" {
		t.Errorf("parseEnvLocal = %v, want [FOO=bar]", got)
	}
}

// TestParseEnvLocal_ValuesWithShellMetachars is the REGRESSION GUARD
// for the v0.2.5 fix. The original failure mode was that the YAML
// post_create script ran `source .env.local` from bash, and bash
// choked on the first DSN line because `(` / `&` / `?` are shell
// metacharacters. The fix bypasses bash's parser by handing parsed
// env entries directly to exec.Cmd.Env, so any byte sequence in the
// value must survive verbatim — including quote characters a
// hand-written post_create append may use: this parser deliberately
// does not attempt shell-style unquoting (see parseEnvLocal's doc
// comment and issue #75 for why that would trade one ambiguity for
// another).
func TestParseEnvLocal_ValuesWithShellMetachars(t *testing.T) {
	src := strings.Join([]string{
		`DEMO_API_DSN=root:@tcp(127.0.0.1:44075)/demo?parseTime=true&loc=UTC`,
		`DEMO_API_URI=grpc://0.0.0.0:47075`,
		`BOUGH_REDIS_PORT=55075`,
		`DEMO_API_RDBURI=redis://127.0.0.1:55075/8`,
		`SHELL_LIKE=$(echo nope)`,
		`WITH_BACKTICKS=` + "`whoami`",
		`WITH_QUOTES="quoted value"`,
		`WITH_SINGLE_QUOTES='single quoted'`,
	}, "\n") + "\n"

	path := writeEnvFile(t, src)
	got := parseEnvLocal(io.Discard, "demo", path)
	want := []string{
		`DEMO_API_DSN=root:@tcp(127.0.0.1:44075)/demo?parseTime=true&loc=UTC`,
		`DEMO_API_URI=grpc://0.0.0.0:47075`,
		`BOUGH_REDIS_PORT=55075`,
		`DEMO_API_RDBURI=redis://127.0.0.1:55075/8`,
		`SHELL_LIKE=$(echo nope)`,
		`WITH_BACKTICKS=` + "`whoami`",
		`WITH_QUOTES="quoted value"`,
		`WITH_SINGLE_QUOTES='single quoted'`,
	}
	if len(got) != len(want) {
		t.Fatalf("parseEnvLocal len = %d, want %d; got=%v", len(got), len(want), got)
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("entry[%d] = %q, want %q", i, got[i], want[i])
		}
	}
}

// TestParseEnvLocal_SkipsCommentsAndBlanks verifies the documented
// dropping behaviour — a `# Auto-generated by bough` header at the
// top of the file must not become an `# Auto-generated by bough` env
// key.
func TestParseEnvLocal_SkipsCommentsAndBlanks(t *testing.T) {
	src := strings.Join([]string{
		`# Auto-generated by bough`,
		``,
		`FOO=bar`,
		``,
		`# Trailing comment`,
		`BAZ=qux`,
		``,
	}, "\n")
	got := parseEnvLocal(io.Discard, "demo", writeEnvFile(t, src))
	want := []string{"FOO=bar", "BAZ=qux"}
	if len(got) != 2 || got[0] != want[0] || got[1] != want[1] {
		t.Errorf("parseEnvLocal = %v, want %v", got, want)
	}
}

// TestParseEnvLocal_DropsMalformed defends against a YAML author who
// pastes a stray heading or `KEY` (no value) into env_local — we drop
// the malformed line rather than panic.
func TestParseEnvLocal_DropsMalformed(t *testing.T) {
	src := "FOO=bar\nKEY_WITHOUT_EQUALS\n=value_without_key\nBAZ=qux\n"
	got := parseEnvLocal(io.Discard, "demo", writeEnvFile(t, src))
	want := []string{"FOO=bar", "BAZ=qux"}
	if len(got) != 2 || got[0] != want[0] || got[1] != want[1] {
		t.Errorf("parseEnvLocal = %v, want %v", got, want)
	}
}

// TestParseEnvLocal_MissingFile keeps the caller's post_create env
// the bare os.Environ() when no .env.local was rendered (e.g. a
// repository with neither env_local nor a db-provider role) — and
// must not log anything for this expected case.
func TestParseEnvLocal_MissingFile(t *testing.T) {
	var buf bytes.Buffer
	got := parseEnvLocal(&buf, "demo", filepath.Join(t.TempDir(), "no-such-file"))
	if got != nil {
		t.Errorf("parseEnvLocal(missing) = %v, want nil", got)
	}
	if buf.Len() != 0 {
		t.Errorf("parseEnvLocal(missing) logged %q, want silence for the expected not-rendered-yet case", buf.String())
	}
}

// TestParseEnvLocal_ReadErrorLogged is the regression guard for the
// #14-review fix: a read failure that is NOT "file does not exist"
// (e.g. the path is a directory, not a file) must be logged with the
// repo name, not collapsed into the same silent nil as the expected
// missing-file case — otherwise a permission/IO problem looks
// identical to "no env_local declared" and the resulting empty
// child-process env is never explained.
func TestParseEnvLocal_ReadErrorLogged(t *testing.T) {
	dir := t.TempDir()
	// A directory at the expected .env.local path: os.ReadFile fails
	// with "is a directory", which is not fs.ErrNotExist.
	envDir := filepath.Join(dir, ".env.local")
	if err := os.Mkdir(envDir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	var buf bytes.Buffer
	got := parseEnvLocal(&buf, "demo", envDir)
	if got != nil {
		t.Errorf("parseEnvLocal(unreadable) = %v, want nil", got)
	}
	if !strings.Contains(buf.String(), "demo") {
		t.Errorf("parseEnvLocal(unreadable) did not log the repo name; got %q", buf.String())
	}
}

// TestPostCreate_HeredocSeesEnvLocalVars is the end-to-end regression
// guard for the actual v0.2.5 bug: a bash `-c` post_create script
// must be able to expand `${BOUGH_REDIS_PORT}` (and friends) inside a
// heredoc *even when* the same .env.local also contains shell-hostile
// values like `DEMO_API_DSN=...tcp(...)/...?parseTime=true&loc=UTC`.
//
// Before the fix the script tried `source .env.local`, bash aborted
// the source on the DSN line's `(`, and `${BOUGH_REDIS_PORT}`
// substituted to empty — producing the literal `redis://127.0.0.1:/8`
// string that crashed the demo-api boot.
//
// After the fix bough hands parsed env entries directly to exec.Cmd
// .Env, so the bash script never invokes its own parser on the file.
// This test asserts the post-fix behaviour by running the same
// bash-with-heredoc pattern bough uses in production.
func TestPostCreate_HeredocSeesEnvLocalVars(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not on PATH")
	}

	dir := t.TempDir()
	envLocal := strings.Join([]string{
		`# Auto-generated by bough — fixture mirroring a demo-api worktree.`,
		`DEMO_API_DISABLE_PORT_FALLBACK=true`,
		`DEMO_API_DSN=root:@tcp(127.0.0.1:44075)/demo?parseTime=true&loc=UTC`,
		`DEMO_API_URI=grpc://0.0.0.0:47075`,
		`BOUGH_REDIS_HOST=127.0.0.1`,
		`BOUGH_REDIS_PORT=55075`,
		`BOUGH_ELASTICSEARCH_URL=http://127.0.0.1:58075`,
	}, "\n") + "\n"
	envPath := filepath.Join(dir, ".env.local")
	if err := os.WriteFile(envPath, []byte(envLocal), 0o644); err != nil {
		t.Fatalf("write .env.local: %v", err)
	}

	// The same heredoc pattern a production monorepo post_create entry would use,
	// minus the historical `set -a; source .env.local; set +a`
	// preamble that the v0.2.5 fix renders unnecessary.
	script := `cat >> .env.local <<EOF

# composition derived from bough plugin EnvVars
DEMO_API_RDBURI=redis://127.0.0.1:${BOUGH_REDIS_PORT}/8
DEMO_API_DLMURI=redis://127.0.0.1:${BOUGH_REDIS_PORT}/7
DEMO_API_ESURL=${BOUGH_ELASTICSEARCH_URL}
EOF`

	c := exec.CommandContext(context.Background(), "bash", "-c", script)
	c.Dir = dir
	// Mirror the production wiring: file env merged on top of
	// the inherited os.Environ.
	c.Env = append(os.Environ(), parseEnvLocal(io.Discard, "demo", envPath)...)
	if out, err := c.CombinedOutput(); err != nil {
		t.Fatalf("bash heredoc: %v\n%s", err, out)
	}

	final, err := os.ReadFile(envPath)
	if err != nil {
		t.Fatalf("read final .env.local: %v", err)
	}
	finalStr := string(final)

	wantSubstrings := []string{
		`DEMO_API_RDBURI=redis://127.0.0.1:55075/8`,
		`DEMO_API_DLMURI=redis://127.0.0.1:55075/7`,
		`DEMO_API_ESURL=http://127.0.0.1:58075`,
	}
	for _, want := range wantSubstrings {
		if !strings.Contains(finalStr, want) {
			t.Errorf("appended .env.local missing %q\nfull contents:\n%s", want, finalStr)
		}
	}

	// And explicitly check the FAILURE pattern is gone — the original
	// bug appended `redis://127.0.0.1:/8` (port slot empty).
	if strings.Contains(finalStr, `redis://127.0.0.1:/8`) {
		t.Errorf("post-fix .env.local STILL contains the empty-port URI; bug regressed")
	}
}

// TestRunPostCreateHooks_LaterLineSeesEarlierLinesAppend is the
// regression guard for the #14-review finding: fileEnv used to be
// parsed once per repo before the post_create loop, so a line that
// derived and appended a new value (the documented idiom this whole
// feature exists for) was invisible to every later line in the same
// repo's post_create list. This drives runPostCreateHooks itself
// (not just parseEnvLocal) with two lines — the first appends a var
// derived from an existing one, the second only succeeds if it can
// read that freshly-appended var back out of its own process env.
func TestRunPostCreateHooks_LaterLineSeesEarlierLinesAppend(t *testing.T) {
	if _, err := exec.LookPath("bash"); err != nil {
		t.Skip("bash not on PATH")
	}
	root := t.TempDir()
	repoDst := filepath.Join(root, "demo")
	if err := os.MkdirAll(repoDst, 0o755); err != nil {
		t.Fatalf("mkdir repo dir: %v", err)
	}
	envLocal := "BOUGH_REDIS_PORT=55075\n"
	if err := os.WriteFile(filepath.Join(repoDst, ".env.local"), []byte(envLocal), 0o644); err != nil {
		t.Fatalf("write .env.local: %v", err)
	}

	marker := filepath.Join(root, "second-line-saw-it")
	cfg := &config.Config{
		Repositories: []config.Repository{
			{
				Name: "demo",
				PostCreate: []string{
					// Derive-then-append: the idiom the doc comment on
					// runPostCreateHooks describes. The heredoc delimiter
					// is deliberately unquoted (<<EOF, not <<'EOF') so
					// bash expands ${BOUGH_REDIS_PORT} before writing —
					// a quoted delimiter would suppress expansion and
					// silently defeat this test's own premise.
					`cat >> .env.local <<EOF
DEMO_API_RDBURI=redis://127.0.0.1:${BOUGH_REDIS_PORT}/8
EOF`,
					// This line only sees DEMO_API_RDBURI if fileEnv was
					// re-read after the line above ran.
					`[ -n "$DEMO_API_RDBURI" ] && echo "$DEMO_API_RDBURI" > ` + marker,
				},
			},
		},
	}

	var buf bytes.Buffer
	failed := runPostCreateHooks(context.Background(), &buf, cfg, root, map[string]bool{})
	if len(failed) != 0 {
		t.Fatalf("runPostCreateHooks failed: %v\nlog:\n%s", failed, buf.String())
	}

	got, err := os.ReadFile(marker)
	if err != nil {
		t.Fatalf("second post_create line did not see the first line's appended var (marker file missing): %v\nlog:\n%s", err, buf.String())
	}
	if want := "redis://127.0.0.1:55075/8\n"; string(got) != want {
		t.Errorf("second line saw %q, want %q", got, want)
	}
}

// TestRunPostCreateHooks_SkipsRepo confirms the skip map (shared with
// materializeRepositories' worktree-add failures and, per the #14
// review, renderEnvLocals' render/write failures) actually suppresses
// post_create for that repo rather than running it against an
// absent/stale .env.local.
func TestRunPostCreateHooks_SkipsRepo(t *testing.T) {
	root := t.TempDir()
	marker := filepath.Join(root, "ran")
	cfg := &config.Config{
		Repositories: []config.Repository{
			{Name: "bad-env", PostCreate: []string{"touch " + marker}},
		},
	}
	var buf bytes.Buffer
	failed := runPostCreateHooks(context.Background(), &buf, cfg, root, map[string]bool{"bad-env": true})
	if len(failed) != 0 {
		t.Errorf("runPostCreateHooks on a skipped repo returned failures: %v", failed)
	}
	if _, err := os.Stat(marker); !errors.Is(err, os.ErrNotExist) {
		t.Errorf("post_create ran for a skipped repo (marker file exists)")
	}
}

func writeEnvFile(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), ".env.local")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatalf("write env file: %v", err)
	}
	return path
}
