package envwriter

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func sampleCtx() Context {
	return Context{
		Worktree: WorktreeCtx{Name: "F-Auth", Root: "/wt/root"},
		Repo:     RepoCtx{Name: "demo-api", Path: "/wt/root/demo-api"},
		Mysql:    DBCtx{Port: 42345, Host: "127.0.0.1", Socket: "/tmp/bough-mysql-42345.sock"},
		Ports:    map[string]int{"api": 45123, "gateway": 48045},
	}
}

func TestRender_substitutesAllKnownFields(t *testing.T) {
	env := map[string]string{
		"DEMO_API_DSN":          `root:@tcp(127.0.0.1:{{ .Mysql.Port }})/demo?parseTime=true`,
		"DEMO_API_URI":          `grpc://0.0.0.0:{{ .Ports.api }}`,
		"DEMO_API_GATEWAY_PORT": `{{ .Ports.gateway }}`,
		"REPO_TAG":              `{{ .Repo.Name }}@{{ .Worktree.Name }}`,
	}
	out, err := Render(env, sampleCtx())
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	cases := map[string]string{
		"DEMO_API_DSN":          "root:@tcp(127.0.0.1:42345)/demo?parseTime=true",
		"DEMO_API_URI":          "grpc://0.0.0.0:45123",
		"DEMO_API_GATEWAY_PORT": "48045",
		"REPO_TAG":              "demo-api@F-Auth",
	}
	for k, want := range cases {
		if got := out[k]; got != want {
			t.Errorf("%s: got %q want %q", k, got, want)
		}
	}
}

func TestRender_sprigFunctions(t *testing.T) {
	// Sprig's `default` filter falls back to a literal when the
	// referenced field is the zero value. Monorepo authors lean on this
	// when a DB host is shared across worktrees but a default is
	// still useful for documentation.
	env := map[string]string{
		"DB_HOST": `{{ default "localhost" .Mysql.Host }}`,
		"VERSION": `{{ "1.0.0" | quote }}`,
	}
	out, err := Render(env, sampleCtx())
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if got, want := out["DB_HOST"], "127.0.0.1"; got != want {
		t.Errorf("DB_HOST default: got %q want %q", got, want)
	}
	if got, want := out["VERSION"], `"1.0.0"`; got != want {
		t.Errorf("VERSION quote: got %q want %q", got, want)
	}
}

func TestRender_propagatesParseError(t *testing.T) {
	env := map[string]string{"BAD": `{{ .Unclosed `}
	_, err := Render(env, sampleCtx())
	if err == nil {
		t.Fatalf("expected parse error, got nil")
	}
	if !strings.Contains(err.Error(), "BAD") {
		t.Errorf("error %q should name the offending key (BAD)", err.Error())
	}
}

func TestRender_propagatesExecuteError_missingKey(t *testing.T) {
	// missingkey=error catches `{{ .Ports.does_not_exist }}` so a YAML
	// typo never silently inserts a blank port into a DSN.
	env := map[string]string{"BAD": `{{ .Ports.does_not_exist }}`}
	_, err := Render(env, sampleCtx())
	if err == nil {
		t.Fatalf("expected missingkey error, got nil")
	}
	if !strings.Contains(err.Error(), "BAD") {
		t.Errorf("error %q should name the offending key (BAD)", err.Error())
	}
}

func TestWrite_sortedKeysAndBanner(t *testing.T) {
	tmp := t.TempDir()
	dst := filepath.Join(tmp, "subdir", ".env.local")
	env := map[string]string{
		"DEMO_API_GATEWAY_PORT": "48045",
		"DEMO_API_DSN":          "dsn",
		"DEMO_API_URI":          "grpc://0.0.0.0:45123",
	}
	if err := Write(dst, env); err != nil {
		t.Fatalf("Write: %v", err)
	}
	raw, err := os.ReadFile(dst)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	contents := string(raw)
	if !strings.HasPrefix(contents, "# Auto-generated by bough") {
		t.Errorf("missing banner: head=%q", contents[:64])
	}
	// Keys must appear in lexicographic order (deterministic output).
	want := []string{
		"DEMO_API_DSN=dsn",
		"DEMO_API_GATEWAY_PORT=48045",
		"DEMO_API_URI=grpc://0.0.0.0:45123",
	}
	pos := 0
	for _, line := range want {
		idx := strings.Index(contents[pos:], line)
		if idx < 0 {
			t.Fatalf("line %q not found at or after pos %d", line, pos)
		}
		pos += idx + len(line)
	}
}

func TestWrite_createsParentDir(t *testing.T) {
	tmp := t.TempDir()
	dst := filepath.Join(tmp, "deep", "nested", "path", ".env.local")
	if err := Write(dst, map[string]string{"K": "v"}); err != nil {
		t.Fatalf("Write: %v", err)
	}
	if _, err := os.Stat(dst); err != nil {
		t.Errorf("Write should have created parent dirs: %v", err)
	}
}
