// Package envwriter materialises the per-worktree `.env.local` files
// declared in `.bough.yaml` under `repositories[].env_local`.
//
// Each YAML value is treated as a text/template + Sprig template so the
// monorepo author can write `{{ .Mysql.Port }}` or `{{ default "127.0.0.1"
// .Mysql.Host }}` and have the deterministic-port output substituted at
// `bough create` time. The rendered key=value lines land at
// `<worktree>/<repo>/.env.local`, prefixed by a fixed banner comment so
// a future reader knows the file is owned by bough and not by hand.
//
// On-disk shape is plain `KEY=value\n` lines with no shell quoting;
// direnv's `dotenv_if_exists .env.local` is what consumes it.
package envwriter

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/Masterminds/sprig/v3"
)

// Context is the variable surface every YAML template renders against.
// Adding a field here is a schema break for monorepo authors — keep the
// surface narrow.
type Context struct {
	Worktree WorktreeCtx
	Repo     RepoCtx
	Mysql    DBCtx
	Ports    map[string]int
}

// WorktreeCtx is the per-worktree identity. `Name` is what the user
// passes to `claude --worktree`; `Root` is the absolute path of
// `<monorepo>/.worktrees/<name>`.
type WorktreeCtx struct {
	Name string
	Root string
}

// RepoCtx is the per-repository identity within a worktree. The host
// renders one .env.local per repository so the template can reference
// the surrounding repo (e.g. for log path naming).
type RepoCtx struct {
	Name string
	Path string
}

// DBCtx is the per-worktree mysql instance descriptor produced by the
// mysql plugin. `Socket` is the absolute /tmp socket path bough has
// configured the mysqld to bind, mostly relevant when a consumer wants
// to skip TCP entirely. When no database plugin is in play the zero
// value is fine — templates that reference DBCtx in a no-DB monorepo
// produce a literal `0` / empty string and surface as a schema error
// upstream rather than here.
type DBCtx struct {
	Port   int
	Host   string
	Socket string
}

// Render runs every value in `env` as a text/template against `ctx` and
// returns the substituted map. Sprig's text-mode funcMap is mixed in so
// monorepo authors can use `default`, `quote`, `replace`, etc. Errors
// pinpoint which key failed — without that the .env.local payload was
// historically the hardest part of a misconfigured worktree to debug.
func Render(env map[string]string, ctx Context) (map[string]string, error) {
	funcs := sprig.TxtFuncMap()
	out := make(map[string]string, len(env))
	for k, v := range env {
		tpl, err := template.New(k).Option("missingkey=error").Funcs(funcs).Parse(v)
		if err != nil {
			return nil, fmt.Errorf("envwriter: parse %s: %w", k, err)
		}
		var buf bytes.Buffer
		if err := tpl.Execute(&buf, ctx); err != nil {
			return nil, fmt.Errorf("envwriter: execute %s: %w", k, err)
		}
		out[k] = buf.String()
	}
	return out, nil
}

// Write serialises `env` to `<path>` as `KEY=value\n` lines preceded by
// the bough banner. Keys are sorted lexicographically so re-rendering
// the same env map produces a byte-identical file (the CI diff stays
// noise-free even when the YAML rewrites under us).
//
// The destination directory is created if absent so the host can
// invoke Write before the consuming repo has had its first `direnv
// allow`.
func Write(path string, env map[string]string) error {
	dir := filepath.Dir(path)
	if dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("envwriter: mkdir %s: %w", dir, err)
		}
	}
	var sb strings.Builder
	sb.WriteString("# Auto-generated by bough — per-worktree port + engine isolation.\n")
	sb.WriteString("# Do not commit. Manage via `.bough.yaml` at the monorepo root.\n")
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		fmt.Fprintf(&sb, "%s=%s\n", k, env[k])
	}
	return os.WriteFile(path, []byte(sb.String()), 0o644)
}
