// instinct.proto is the v0.5.0 contract between the bough host and any
// `bough-plugin-instinct-<name>` binary that mints InstinctCandidates
// from raw TraceBundles. The bough core ships a default in-process
// minter (`internal/instinct.builtin_minter`) so this interface is
// only used when a user wires up an LLM-backed candidate generator
// (v0.6+ experimental, e.g. SkillX / Anything2Skill adapters).
//
// Why the split from MemoryBackend: memory backends (mem0, Graphiti)
// are good at storage and retrieval, not at the bough-specific
// concern of distilling a per-worktree trace into a behavioural rule.
// Forcing every memory backend to implement Mint would push bough's
// trace-handling logic into every plugin author's lap; isolating it
// here keeps MemoryBackend authors focused on persistence.
//
// Versioning: bumping ProtocolVersion in plugins/instinct/api/handshake.go
// is what gates a backwards-incompatible change here. v0.6 may add
// an InstinctScorer or InstinctMerger RPC alongside Mint.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: instinct.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InstinctMinter_Mint_FullMethodName = "/bough.instinct.v1.InstinctMinter/Mint"
)

// InstinctMinterClient is the client API for InstinctMinter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InstinctMinter turns observed traces (session log lines, test
// failures, lint output, commit messages, post-create hook output)
// into one or more InstinctCandidate rows that the host's poisoning
// guard then routes through approval before they become active.
type InstinctMinterClient interface {
	// Mint inspects the bundle of traces in TraceBundles and returns
	// zero or more candidates. Plugins should be lenient: returning an
	// empty Candidates list is fine when the bundle does not carry
	// enough signal. The host is responsible for dedupe (sha256 over
	// rule + scope) and for budget/poisoning enforcement; minters
	// should focus on quality of extraction, not on whether a
	// candidate "deserves" to be stored.
	Mint(ctx context.Context, in *MintRequest, opts ...grpc.CallOption) (*MintResponse, error)
}

type instinctMinterClient struct {
	cc grpc.ClientConnInterface
}

func NewInstinctMinterClient(cc grpc.ClientConnInterface) InstinctMinterClient {
	return &instinctMinterClient{cc}
}

func (c *instinctMinterClient) Mint(ctx context.Context, in *MintRequest, opts ...grpc.CallOption) (*MintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MintResponse)
	err := c.cc.Invoke(ctx, InstinctMinter_Mint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InstinctMinterServer is the server API for InstinctMinter service.
// All implementations must embed UnimplementedInstinctMinterServer
// for forward compatibility.
//
// InstinctMinter turns observed traces (session log lines, test
// failures, lint output, commit messages, post-create hook output)
// into one or more InstinctCandidate rows that the host's poisoning
// guard then routes through approval before they become active.
type InstinctMinterServer interface {
	// Mint inspects the bundle of traces in TraceBundles and returns
	// zero or more candidates. Plugins should be lenient: returning an
	// empty Candidates list is fine when the bundle does not carry
	// enough signal. The host is responsible for dedupe (sha256 over
	// rule + scope) and for budget/poisoning enforcement; minters
	// should focus on quality of extraction, not on whether a
	// candidate "deserves" to be stored.
	Mint(context.Context, *MintRequest) (*MintResponse, error)
	mustEmbedUnimplementedInstinctMinterServer()
}

// UnimplementedInstinctMinterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInstinctMinterServer struct{}

func (UnimplementedInstinctMinterServer) Mint(context.Context, *MintRequest) (*MintResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Mint not implemented")
}
func (UnimplementedInstinctMinterServer) mustEmbedUnimplementedInstinctMinterServer() {}
func (UnimplementedInstinctMinterServer) testEmbeddedByValue()                        {}

// UnsafeInstinctMinterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InstinctMinterServer will
// result in compilation errors.
type UnsafeInstinctMinterServer interface {
	mustEmbedUnimplementedInstinctMinterServer()
}

func RegisterInstinctMinterServer(s grpc.ServiceRegistrar, srv InstinctMinterServer) {
	// If the following call panics, it indicates UnimplementedInstinctMinterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InstinctMinter_ServiceDesc, srv)
}

func _InstinctMinter_Mint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InstinctMinterServer).Mint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InstinctMinter_Mint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InstinctMinterServer).Mint(ctx, req.(*MintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InstinctMinter_ServiceDesc is the grpc.ServiceDesc for InstinctMinter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InstinctMinter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bough.instinct.v1.InstinctMinter",
	HandlerType: (*InstinctMinterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Mint",
			Handler:    _InstinctMinter_Mint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "instinct.proto",
}
