// instinct.proto is the v0.5.0 contract between the bough host and any
// `bough-plugin-instinct-<name>` binary that mints InstinctCandidates
// from raw TraceBundles. The bough core ships a default in-process
// minter (`internal/instinct.builtin_minter`) so this interface is
// only used when a user wires up an LLM-backed candidate generator
// (v0.6+ experimental, e.g. SkillX / Anything2Skill adapters).
//
// Why the split from MemoryBackend: memory backends (mem0, Graphiti)
// are good at storage and retrieval, not at the bough-specific
// concern of distilling a per-worktree trace into a behavioural rule.
// Forcing every memory backend to implement Mint would push bough's
// trace-handling logic into every plugin author's lap; isolating it
// here keeps MemoryBackend authors focused on persistence.
//
// Versioning: bumping ProtocolVersion in plugins/instinct/api/handshake.go
// is what gates a backwards-incompatible change here. v0.6 may add
// an InstinctScorer or InstinctMerger RPC alongside Mint.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: instinct.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scope addresses one of three lifetime tiers, mirroring
// plugins/memory/api/proto.Scope. Duplicated here so the instinct
// plugin contract is independently complete.
type Scope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "worktree" | "repo" | "global"
	WorktreeId    string                 `protobuf:"bytes,2,opt,name=worktree_id,json=worktreeId,proto3" json:"worktree_id,omitempty"`
	RepoName      string                 `protobuf:"bytes,3,opt,name=repo_name,json=repoName,proto3" json:"repo_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_instinct_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_instinct_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_instinct_proto_rawDescGZIP(), []int{0}
}

func (x *Scope) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Scope) GetWorktreeId() string {
	if x != nil {
		return x.WorktreeId
	}
	return ""
}

func (x *Scope) GetRepoName() string {
	if x != nil {
		return x.RepoName
	}
	return ""
}

// TraceBundle is a normalised observation passed from the host's
// observer (stdin ingest in v0.5 primary path, jsonl tail in opt-in
// beta) after redaction has stripped PII/secret patterns.
type TraceBundle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"` // stdin | session_log | test_failure | lint_output | commit_message | post_create_hook
	Scope         *Scope                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	CapturedAt    int64                  `protobuf:"varint,4,opt,name=captured_at,json=capturedAt,proto3" json:"captured_at,omitempty"`           // unix epoch seconds
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`                                    // redacted raw text
	EvidenceRef   string                 `protobuf:"bytes,6,opt,name=evidence_ref,json=evidenceRef,proto3" json:"evidence_ref,omitempty"`         // session id, commit hash, test id, etc.
	SourceEventId string                 `protobuf:"bytes,7,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"` // idempotency token for retry-safe ingest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceBundle) Reset() {
	*x = TraceBundle{}
	mi := &file_instinct_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceBundle) ProtoMessage() {}

func (x *TraceBundle) ProtoReflect() protoreflect.Message {
	mi := &file_instinct_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceBundle.ProtoReflect.Descriptor instead.
func (*TraceBundle) Descriptor() ([]byte, []int) {
	return file_instinct_proto_rawDescGZIP(), []int{1}
}

func (x *TraceBundle) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TraceBundle) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *TraceBundle) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *TraceBundle) GetCapturedAt() int64 {
	if x != nil {
		return x.CapturedAt
	}
	return 0
}

func (x *TraceBundle) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *TraceBundle) GetEvidenceRef() string {
	if x != nil {
		return x.EvidenceRef
	}
	return ""
}

func (x *TraceBundle) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

// InstinctCandidate is the unit a minter produces and the host
// considers for approval. Confidence is the minter's best estimate
// based on the candidate's source; the host clamps it to
// `instinct.confidence.sources.<source>` if the value is higher than
// the configured ceiling.
type InstinctCandidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Rule          string                 `protobuf:"bytes,2,opt,name=rule,proto3" json:"rule,omitempty"`
	Why           string                 `protobuf:"bytes,3,opt,name=why,proto3" json:"why,omitempty"`
	HowToApply    string                 `protobuf:"bytes,4,opt,name=how_to_apply,json=howToApply,proto3" json:"how_to_apply,omitempty"`
	Domain        []string               `protobuf:"bytes,5,rep,name=domain,proto3" json:"domain,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	Confidence    float64                `protobuf:"fixed64,8,opt,name=confidence,proto3" json:"confidence,omitempty"`
	State         string                 `protobuf:"bytes,9,opt,name=state,proto3" json:"state,omitempty"` // always "candidate" out of Mint
	SourceTraces  []string               `protobuf:"bytes,10,rep,name=source_traces,json=sourceTraces,proto3" json:"source_traces,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DedupeKey     string                 `protobuf:"bytes,12,opt,name=dedupe_key,json=dedupeKey,proto3" json:"dedupe_key,omitempty"` // sha256(normalize(rule + scope))
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstinctCandidate) Reset() {
	*x = InstinctCandidate{}
	mi := &file_instinct_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstinctCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstinctCandidate) ProtoMessage() {}

func (x *InstinctCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_instinct_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstinctCandidate.ProtoReflect.Descriptor instead.
func (*InstinctCandidate) Descriptor() ([]byte, []int) {
	return file_instinct_proto_rawDescGZIP(), []int{2}
}

func (x *InstinctCandidate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstinctCandidate) GetRule() string {
	if x != nil {
		return x.Rule
	}
	return ""
}

func (x *InstinctCandidate) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

func (x *InstinctCandidate) GetHowToApply() string {
	if x != nil {
		return x.HowToApply
	}
	return ""
}

func (x *InstinctCandidate) GetDomain() []string {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *InstinctCandidate) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *InstinctCandidate) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *InstinctCandidate) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *InstinctCandidate) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InstinctCandidate) GetSourceTraces() []string {
	if x != nil {
		return x.SourceTraces
	}
	return nil
}

func (x *InstinctCandidate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *InstinctCandidate) GetDedupeKey() string {
	if x != nil {
		return x.DedupeKey
	}
	return ""
}

type MintRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceBundles  []*TraceBundle         `protobuf:"bytes,1,rep,name=trace_bundles,json=traceBundles,proto3" json:"trace_bundles,omitempty"`
	Scope         *Scope                 `protobuf:"bytes,2,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintRequest) Reset() {
	*x = MintRequest{}
	mi := &file_instinct_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintRequest) ProtoMessage() {}

func (x *MintRequest) ProtoReflect() protoreflect.Message {
	mi := &file_instinct_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintRequest.ProtoReflect.Descriptor instead.
func (*MintRequest) Descriptor() ([]byte, []int) {
	return file_instinct_proto_rawDescGZIP(), []int{3}
}

func (x *MintRequest) GetTraceBundles() []*TraceBundle {
	if x != nil {
		return x.TraceBundles
	}
	return nil
}

func (x *MintRequest) GetScope() *Scope {
	if x != nil {
		return x.Scope
	}
	return nil
}

type MintResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Candidates    []*InstinctCandidate   `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MintResponse) Reset() {
	*x = MintResponse{}
	mi := &file_instinct_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MintResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MintResponse) ProtoMessage() {}

func (x *MintResponse) ProtoReflect() protoreflect.Message {
	mi := &file_instinct_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MintResponse.ProtoReflect.Descriptor instead.
func (*MintResponse) Descriptor() ([]byte, []int) {
	return file_instinct_proto_rawDescGZIP(), []int{4}
}

func (x *MintResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *MintResponse) GetCandidates() []*InstinctCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

var File_instinct_proto protoreflect.FileDescriptor

const file_instinct_proto_rawDesc = "" +
	"\n" +
	"\x0einstinct.proto\x12\x11bough.instinct.v1\"[\n" +
	"\x05Scope\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1f\n" +
	"\vworktree_id\x18\x02 \x01(\tR\n" +
	"worktreeId\x12\x1b\n" +
	"\trepo_name\x18\x03 \x01(\tR\brepoName\"\xeb\x01\n" +
	"\vTraceBundle\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12.\n" +
	"\x05scope\x18\x03 \x01(\v2\x18.bough.instinct.v1.ScopeR\x05scope\x12\x1f\n" +
	"\vcaptured_at\x18\x04 \x01(\x03R\n" +
	"capturedAt\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12!\n" +
	"\fevidence_ref\x18\x06 \x01(\tR\vevidenceRef\x12&\n" +
	"\x0fsource_event_id\x18\a \x01(\tR\rsourceEventId\"\xe4\x02\n" +
	"\x11InstinctCandidate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04rule\x18\x02 \x01(\tR\x04rule\x12\x10\n" +
	"\x03why\x18\x03 \x01(\tR\x03why\x12 \n" +
	"\fhow_to_apply\x18\x04 \x01(\tR\n" +
	"howToApply\x12\x16\n" +
	"\x06domain\x18\x05 \x03(\tR\x06domain\x12.\n" +
	"\x05scope\x18\x06 \x01(\v2\x18.bough.instinct.v1.ScopeR\x05scope\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\x12\x1e\n" +
	"\n" +
	"confidence\x18\b \x01(\x01R\n" +
	"confidence\x12\x14\n" +
	"\x05state\x18\t \x01(\tR\x05state\x12#\n" +
	"\rsource_traces\x18\n" +
	" \x03(\tR\fsourceTraces\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"dedupe_key\x18\f \x01(\tR\tdedupeKey\"\x82\x01\n" +
	"\vMintRequest\x12C\n" +
	"\rtrace_bundles\x18\x01 \x03(\v2\x1e.bough.instinct.v1.TraceBundleR\ftraceBundles\x12.\n" +
	"\x05scope\x18\x02 \x01(\v2\x18.bough.instinct.v1.ScopeR\x05scope\"j\n" +
	"\fMintResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12D\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2$.bough.instinct.v1.InstinctCandidateR\n" +
	"candidates2Y\n" +
	"\x0eInstinctMinter\x12G\n" +
	"\x04Mint\x12\x1e.bough.instinct.v1.MintRequest\x1a\x1f.bough.instinct.v1.MintResponseB=Z;github.com/ikeikeikeike/bough/plugins/instinct/api/proto;pbb\x06proto3"

var (
	file_instinct_proto_rawDescOnce sync.Once
	file_instinct_proto_rawDescData []byte
)

func file_instinct_proto_rawDescGZIP() []byte {
	file_instinct_proto_rawDescOnce.Do(func() {
		file_instinct_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instinct_proto_rawDesc), len(file_instinct_proto_rawDesc)))
	})
	return file_instinct_proto_rawDescData
}

var file_instinct_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_instinct_proto_goTypes = []any{
	(*Scope)(nil),             // 0: bough.instinct.v1.Scope
	(*TraceBundle)(nil),       // 1: bough.instinct.v1.TraceBundle
	(*InstinctCandidate)(nil), // 2: bough.instinct.v1.InstinctCandidate
	(*MintRequest)(nil),       // 3: bough.instinct.v1.MintRequest
	(*MintResponse)(nil),      // 4: bough.instinct.v1.MintResponse
}
var file_instinct_proto_depIdxs = []int32{
	0, // 0: bough.instinct.v1.TraceBundle.scope:type_name -> bough.instinct.v1.Scope
	0, // 1: bough.instinct.v1.InstinctCandidate.scope:type_name -> bough.instinct.v1.Scope
	1, // 2: bough.instinct.v1.MintRequest.trace_bundles:type_name -> bough.instinct.v1.TraceBundle
	0, // 3: bough.instinct.v1.MintRequest.scope:type_name -> bough.instinct.v1.Scope
	2, // 4: bough.instinct.v1.MintResponse.candidates:type_name -> bough.instinct.v1.InstinctCandidate
	3, // 5: bough.instinct.v1.InstinctMinter.Mint:input_type -> bough.instinct.v1.MintRequest
	4, // 6: bough.instinct.v1.InstinctMinter.Mint:output_type -> bough.instinct.v1.MintResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_instinct_proto_init() }
func file_instinct_proto_init() {
	if File_instinct_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instinct_proto_rawDesc), len(file_instinct_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_instinct_proto_goTypes,
		DependencyIndexes: file_instinct_proto_depIdxs,
		MessageInfos:      file_instinct_proto_msgTypes,
	}.Build()
	File_instinct_proto = out.File
	file_instinct_proto_goTypes = nil
	file_instinct_proto_depIdxs = nil
}
