// evaluator.proto freezes the v0.5.0 wire contract for
// `bough-plugin-evaluator-<name>` plugins WITHOUT shipping a working
// implementation. v0.5 only generates the gRPC stubs and the Go
// interface; the host's `bough capability evaluate` CLI and the first
// official evaluators (GEPA reflective prompt optimiser, TextGrad
// gradient evaluator, MUSE-Autoskill lifecycle evaluator, SkillAudit
// paired-trajectory auditor) land in v0.7+.
//
// Why split this from CapabilityCompiler: compilation and evaluation
// are different concerns. A compiler turns approved instincts into
// candidate artifacts; an evaluator decides whether a given artifact
// should survive (be promoted), be revised, or be pruned. The bough
// vision treats evaluator-driven evolution (utility scoring, auto-
// pruning, paired-trajectory auditing) as the v0.7+ layer that sits
// above v0.6's compiler layer. Keeping the interfaces separate means
// a v0.7 evaluator can score artifacts produced by any v0.6 compiler
// without the compiler having to expose an evaluate hook.
//
// Versioning: bumping ProtocolVersion in plugins/evaluator/api/handshake.go
// is what gates a backwards-incompatible change here. Recommendation
// fields may grow over time (e.g., a recommended next experiment
// when ShouldPrune is false), but the wire shape stays stable.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: evaluator.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SkillEvaluator_Evaluate_FullMethodName = "/bough.evaluator.v1.SkillEvaluator/Evaluate"
)

// SkillEvaluatorClient is the client API for SkillEvaluator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SkillEvaluator scores a single CapabilityArtifact and recommends
// whether the host should promote, revise, or prune it. Evaluators
// are stateless from the host's point of view; if an evaluator needs
// historical context (paired-trajectory comparisons, prior
// confidence trajectory) it must fetch that from its own backing
// store, not from bough's memory.
type SkillEvaluatorClient interface {
	Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error)
}

type skillEvaluatorClient struct {
	cc grpc.ClientConnInterface
}

func NewSkillEvaluatorClient(cc grpc.ClientConnInterface) SkillEvaluatorClient {
	return &skillEvaluatorClient{cc}
}

func (c *skillEvaluatorClient) Evaluate(ctx context.Context, in *EvaluateRequest, opts ...grpc.CallOption) (*EvaluateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateResponse)
	err := c.cc.Invoke(ctx, SkillEvaluator_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SkillEvaluatorServer is the server API for SkillEvaluator service.
// All implementations must embed UnimplementedSkillEvaluatorServer
// for forward compatibility.
//
// SkillEvaluator scores a single CapabilityArtifact and recommends
// whether the host should promote, revise, or prune it. Evaluators
// are stateless from the host's point of view; if an evaluator needs
// historical context (paired-trajectory comparisons, prior
// confidence trajectory) it must fetch that from its own backing
// store, not from bough's memory.
type SkillEvaluatorServer interface {
	Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error)
	mustEmbedUnimplementedSkillEvaluatorServer()
}

// UnimplementedSkillEvaluatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSkillEvaluatorServer struct{}

func (UnimplementedSkillEvaluatorServer) Evaluate(context.Context, *EvaluateRequest) (*EvaluateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedSkillEvaluatorServer) mustEmbedUnimplementedSkillEvaluatorServer() {}
func (UnimplementedSkillEvaluatorServer) testEmbeddedByValue()                        {}

// UnsafeSkillEvaluatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SkillEvaluatorServer will
// result in compilation errors.
type UnsafeSkillEvaluatorServer interface {
	mustEmbedUnimplementedSkillEvaluatorServer()
}

func RegisterSkillEvaluatorServer(s grpc.ServiceRegistrar, srv SkillEvaluatorServer) {
	// If the following call panics, it indicates UnimplementedSkillEvaluatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SkillEvaluator_ServiceDesc, srv)
}

func _SkillEvaluator_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SkillEvaluatorServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SkillEvaluator_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SkillEvaluatorServer).Evaluate(ctx, req.(*EvaluateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SkillEvaluator_ServiceDesc is the grpc.ServiceDesc for SkillEvaluator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SkillEvaluator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bough.evaluator.v1.SkillEvaluator",
	HandlerType: (*SkillEvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _SkillEvaluator_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "evaluator.proto",
}
