// evaluator.proto freezes the v0.5.0 wire contract for
// `bough-plugin-evaluator-<name>` plugins WITHOUT shipping a working
// implementation. v0.5 only generates the gRPC stubs and the Go
// interface; the host's `bough capability evaluate` CLI and the first
// official evaluators (GEPA reflective prompt optimiser, TextGrad
// gradient evaluator, MUSE-Autoskill lifecycle evaluator, SkillAudit
// paired-trajectory auditor) land in v0.7+.
//
// Why split this from CapabilityCompiler: compilation and evaluation
// are different concerns. A compiler turns approved instincts into
// candidate artifacts; an evaluator decides whether a given artifact
// should survive (be promoted), be revised, or be pruned. The bough
// vision treats evaluator-driven evolution (utility scoring, auto-
// pruning, paired-trajectory auditing) as the v0.7+ layer that sits
// above v0.6's compiler layer. Keeping the interfaces separate means
// a v0.7 evaluator can score artifacts produced by any v0.6 compiler
// without the compiler having to expose an evaluate hook.
//
// Versioning: bumping ProtocolVersion in plugins/evaluator/api/handshake.go
// is what gates a backwards-incompatible change here. Recommendation
// fields may grow over time (e.g., a recommended next experiment
// when ShouldPrune is false), but the wire shape stays stable.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: evaluator.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EvaluationOutcome is the evaluator's coarse-grained verdict. Fine-
// grained signals (utility breakdown, regression evidence) live on
// EvaluateResponse fields below; OUTCOME is the routing decision the
// host's coordinator uses.
type EvaluationOutcome int32

const (
	EvaluationOutcome_OUTCOME_UNSPECIFIED EvaluationOutcome = 0
	EvaluationOutcome_OUTCOME_PROMOTE     EvaluationOutcome = 1
	EvaluationOutcome_OUTCOME_KEEP        EvaluationOutcome = 2
	EvaluationOutcome_OUTCOME_REVISE      EvaluationOutcome = 3
	EvaluationOutcome_OUTCOME_PRUNE       EvaluationOutcome = 4
)

// Enum value maps for EvaluationOutcome.
var (
	EvaluationOutcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_PROMOTE",
		2: "OUTCOME_KEEP",
		3: "OUTCOME_REVISE",
		4: "OUTCOME_PRUNE",
	}
	EvaluationOutcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED": 0,
		"OUTCOME_PROMOTE":     1,
		"OUTCOME_KEEP":        2,
		"OUTCOME_REVISE":      3,
		"OUTCOME_PRUNE":       4,
	}
)

func (x EvaluationOutcome) Enum() *EvaluationOutcome {
	p := new(EvaluationOutcome)
	*p = x
	return p
}

func (x EvaluationOutcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EvaluationOutcome) Descriptor() protoreflect.EnumDescriptor {
	return file_evaluator_proto_enumTypes[0].Descriptor()
}

func (EvaluationOutcome) Type() protoreflect.EnumType {
	return &file_evaluator_proto_enumTypes[0]
}

func (x EvaluationOutcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EvaluationOutcome.Descriptor instead.
func (EvaluationOutcome) EnumDescriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{0}
}

// EvaluateRequest passes the artifact as opaque JSON bytes rather
// than importing plugins/capability/api/proto/capability.proto.
// Decoupling lets evaluator plugins (v0.7+) ship without picking up
// a transitive proto dependency on the capability surface — the host
// marshals the schema.CapabilityArtifact to JSON before invoking
// Evaluate.
type EvaluateRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId           string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ArtifactJson         []byte                 `protobuf:"bytes,2,opt,name=artifact_json,json=artifactJson,proto3" json:"artifact_json,omitempty"`
	EvaluatorContextJson []byte                 `protobuf:"bytes,3,opt,name=evaluator_context_json,json=evaluatorContextJson,proto3" json:"evaluator_context_json,omitempty"` // free-form plugin-defined inputs
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EvaluateRequest) Reset() {
	*x = EvaluateRequest{}
	mi := &file_evaluator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRequest) ProtoMessage() {}

func (x *EvaluateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRequest) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{0}
}

func (x *EvaluateRequest) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *EvaluateRequest) GetArtifactJson() []byte {
	if x != nil {
		return x.ArtifactJson
	}
	return nil
}

func (x *EvaluateRequest) GetEvaluatorContextJson() []byte {
	if x != nil {
		return x.EvaluatorContextJson
	}
	return nil
}

type EvaluateResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Error                string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Outcome              EvaluationOutcome      `protobuf:"varint,2,opt,name=outcome,proto3,enum=bough.evaluator.v1.EvaluationOutcome" json:"outcome,omitempty"`
	Utility              float64                `protobuf:"fixed64,3,opt,name=utility,proto3" json:"utility,omitempty"`                                        // [0.0, 1.0], evaluator's confidence
	ConfidenceDelta      float64                `protobuf:"fixed64,4,opt,name=confidence_delta,json=confidenceDelta,proto3" json:"confidence_delta,omitempty"` // suggested confidence adjustment
	ShouldPrune          bool                   `protobuf:"varint,5,opt,name=should_prune,json=shouldPrune,proto3" json:"should_prune,omitempty"`              // OUTCOME_PRUNE convenience flag
	EvidenceRefs         []string               `protobuf:"bytes,6,rep,name=evidence_refs,json=evidenceRefs,proto3" json:"evidence_refs,omitempty"`
	Explanation          string                 `protobuf:"bytes,7,opt,name=explanation,proto3" json:"explanation,omitempty"`                                                 // human-readable reasoning
	EvaluatorPayloadJson []byte                 `protobuf:"bytes,8,opt,name=evaluator_payload_json,json=evaluatorPayloadJson,proto3" json:"evaluator_payload_json,omitempty"` // free-form plugin-defined output
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *EvaluateResponse) Reset() {
	*x = EvaluateResponse{}
	mi := &file_evaluator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateResponse) ProtoMessage() {}

func (x *EvaluateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_evaluator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateResponse.ProtoReflect.Descriptor instead.
func (*EvaluateResponse) Descriptor() ([]byte, []int) {
	return file_evaluator_proto_rawDescGZIP(), []int{1}
}

func (x *EvaluateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *EvaluateResponse) GetOutcome() EvaluationOutcome {
	if x != nil {
		return x.Outcome
	}
	return EvaluationOutcome_OUTCOME_UNSPECIFIED
}

func (x *EvaluateResponse) GetUtility() float64 {
	if x != nil {
		return x.Utility
	}
	return 0
}

func (x *EvaluateResponse) GetConfidenceDelta() float64 {
	if x != nil {
		return x.ConfidenceDelta
	}
	return 0
}

func (x *EvaluateResponse) GetShouldPrune() bool {
	if x != nil {
		return x.ShouldPrune
	}
	return false
}

func (x *EvaluateResponse) GetEvidenceRefs() []string {
	if x != nil {
		return x.EvidenceRefs
	}
	return nil
}

func (x *EvaluateResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

func (x *EvaluateResponse) GetEvaluatorPayloadJson() []byte {
	if x != nil {
		return x.EvaluatorPayloadJson
	}
	return nil
}

var File_evaluator_proto protoreflect.FileDescriptor

const file_evaluator_proto_rawDesc = "" +
	"\n" +
	"\x0fevaluator.proto\x12\x12bough.evaluator.v1\"\x8d\x01\n" +
	"\x0fEvaluateRequest\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12#\n" +
	"\rartifact_json\x18\x02 \x01(\fR\fartifactJson\x124\n" +
	"\x16evaluator_context_json\x18\x03 \x01(\fR\x14evaluatorContextJson\"\xce\x02\n" +
	"\x10EvaluateResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12?\n" +
	"\aoutcome\x18\x02 \x01(\x0e2%.bough.evaluator.v1.EvaluationOutcomeR\aoutcome\x12\x18\n" +
	"\autility\x18\x03 \x01(\x01R\autility\x12)\n" +
	"\x10confidence_delta\x18\x04 \x01(\x01R\x0fconfidenceDelta\x12!\n" +
	"\fshould_prune\x18\x05 \x01(\bR\vshouldPrune\x12#\n" +
	"\revidence_refs\x18\x06 \x03(\tR\fevidenceRefs\x12 \n" +
	"\vexplanation\x18\a \x01(\tR\vexplanation\x124\n" +
	"\x16evaluator_payload_json\x18\b \x01(\fR\x14evaluatorPayloadJson*z\n" +
	"\x11EvaluationOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fOUTCOME_PROMOTE\x10\x01\x12\x10\n" +
	"\fOUTCOME_KEEP\x10\x02\x12\x12\n" +
	"\x0eOUTCOME_REVISE\x10\x03\x12\x11\n" +
	"\rOUTCOME_PRUNE\x10\x042g\n" +
	"\x0eSkillEvaluator\x12U\n" +
	"\bEvaluate\x12#.bough.evaluator.v1.EvaluateRequest\x1a$.bough.evaluator.v1.EvaluateResponseB>Z<github.com/ikeikeikeike/bough/plugins/evaluator/api/proto;pbb\x06proto3"

var (
	file_evaluator_proto_rawDescOnce sync.Once
	file_evaluator_proto_rawDescData []byte
)

func file_evaluator_proto_rawDescGZIP() []byte {
	file_evaluator_proto_rawDescOnce.Do(func() {
		file_evaluator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evaluator_proto_rawDesc), len(file_evaluator_proto_rawDesc)))
	})
	return file_evaluator_proto_rawDescData
}

var file_evaluator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_evaluator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_evaluator_proto_goTypes = []any{
	(EvaluationOutcome)(0),   // 0: bough.evaluator.v1.EvaluationOutcome
	(*EvaluateRequest)(nil),  // 1: bough.evaluator.v1.EvaluateRequest
	(*EvaluateResponse)(nil), // 2: bough.evaluator.v1.EvaluateResponse
}
var file_evaluator_proto_depIdxs = []int32{
	0, // 0: bough.evaluator.v1.EvaluateResponse.outcome:type_name -> bough.evaluator.v1.EvaluationOutcome
	1, // 1: bough.evaluator.v1.SkillEvaluator.Evaluate:input_type -> bough.evaluator.v1.EvaluateRequest
	2, // 2: bough.evaluator.v1.SkillEvaluator.Evaluate:output_type -> bough.evaluator.v1.EvaluateResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_evaluator_proto_init() }
func file_evaluator_proto_init() {
	if File_evaluator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evaluator_proto_rawDesc), len(file_evaluator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_evaluator_proto_goTypes,
		DependencyIndexes: file_evaluator_proto_depIdxs,
		EnumInfos:         file_evaluator_proto_enumTypes,
		MessageInfos:      file_evaluator_proto_msgTypes,
	}.Build()
	File_evaluator_proto = out.File
	file_evaluator_proto_goTypes = nil
	file_evaluator_proto_depIdxs = nil
}
