// engine.proto is the v0.4.0 contract between the bough host and any
// `bough-plugin-<kind>` binary that provisions a per-worktree engine
// instance (database / message broker / object store / search index /
// KV store, etc.). Plugins implement EngineProvider over Hashicorp
// go-plugin's gRPC transport.
//
// Renamed from db.proto in v0.4.0 along with `plugins/db/` →
// `plugins/engine/`. The shape was generalised: `Port int` →
// `repeated PortSpec ports` for multi-port engines (rabbitmq AMQP +
// Management, kafka broker + controller, NATS client + monitor),
// `repeated string initial_databases` → `repeated ResourceSpec
// initial_resources` (DB schema / kafka topic / minio bucket /
// rabbitmq vhost / consul KV). See docs/MIGRATION-v0.3-to-v0.4.md.
//
// Versioning: bumping ProtocolVersion in plugins/engine/api/handshake.go
// is what gates a backwards-incompatible change here. Add new fields
// with new tag numbers, do not renumber existing ones.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: engine.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EngineProvider_Up_FullMethodName               = "/bough.engine.v1.EngineProvider/Up"
	EngineProvider_Down_FullMethodName             = "/bough.engine.v1.EngineProvider/Down"
	EngineProvider_ReadyCheck_FullMethodName       = "/bough.engine.v1.EngineProvider/ReadyCheck"
	EngineProvider_Cleanup_FullMethodName          = "/bough.engine.v1.EngineProvider/Cleanup"
	EngineProvider_PortRangeDefault_FullMethodName = "/bough.engine.v1.EngineProvider/PortRangeDefault"
	EngineProvider_EnvVars_FullMethodName          = "/bough.engine.v1.EngineProvider/EnvVars"
)

// EngineProviderClient is the client API for EngineProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// EngineProvider is the lifecycle of one per-worktree engine instance.
type EngineProviderClient interface {
	// Up starts the engine listening on the host-allocated `ports`, with
	// its data directory anchored at `datadir`. The host passes
	// `worktree_root` so the plugin can resolve a `nix run` invocation
	// against the embedded flake without needing global state, and
	// `initial_resources` so the engine can self-provision (DB schemas,
	// kafka topics, minio buckets — engine-specific by `type`).
	Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpResponse, error)
	// Down asks the plugin to gracefully stop the instance and clean up
	// any supervisor processes it spawned.
	Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (*DownResponse, error)
	// ReadyCheck polls for `timeout_sec` seconds until the instance
	// accepts connections on every entry in `ports`. Returns ready=true
	// only after the engine answers a protocol-level probe (not just
	// TCP listen); the conformance suite enforces this contract.
	ReadyCheck(ctx context.Context, in *ReadyCheckRequest, opts ...grpc.CallOption) (*ReadyCheckResponse, error)
	// Cleanup removes the on-disk data directory after Down has
	// confirmed the instance is no longer running.
	Cleanup(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error)
	// PortRangeDefault returns, per `role`, the [low, high] range the
	// plugin recommends. Single-port engines return one entry keyed
	// `"main"`; multi-port engines return one per role
	// (e.g. {"amqp": [...], "management": [...]} for rabbitmq).
	// Used when the YAML does not override `port_ranges`.
	PortRangeDefault(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PortRangeResponse, error)
	// EnvVars returns the set of environment variables consumers (the
	// host and any sibling repo) should see in their rendered .env.local.
	// For multi-port engines, role-suffixed keys are expected
	// (BOUGH_RABBITMQ_AMQP_PORT, BOUGH_RABBITMQ_MANAGEMENT_PORT, ...);
	// single-port engines keep the v0.3-era role-omitted form
	// (BOUGH_MYSQL_PORT).
	EnvVars(ctx context.Context, in *EnvVarsRequest, opts ...grpc.CallOption) (*EnvVarsResponse, error)
}

type engineProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineProviderClient(cc grpc.ClientConnInterface) EngineProviderClient {
	return &engineProviderClient{cc}
}

func (c *engineProviderClient) Up(ctx context.Context, in *UpRequest, opts ...grpc.CallOption) (*UpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpResponse)
	err := c.cc.Invoke(ctx, EngineProvider_Up_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineProviderClient) Down(ctx context.Context, in *DownRequest, opts ...grpc.CallOption) (*DownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownResponse)
	err := c.cc.Invoke(ctx, EngineProvider_Down_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineProviderClient) ReadyCheck(ctx context.Context, in *ReadyCheckRequest, opts ...grpc.CallOption) (*ReadyCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadyCheckResponse)
	err := c.cc.Invoke(ctx, EngineProvider_ReadyCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineProviderClient) Cleanup(ctx context.Context, in *CleanupRequest, opts ...grpc.CallOption) (*CleanupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CleanupResponse)
	err := c.cc.Invoke(ctx, EngineProvider_Cleanup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineProviderClient) PortRangeDefault(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PortRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PortRangeResponse)
	err := c.cc.Invoke(ctx, EngineProvider_PortRangeDefault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineProviderClient) EnvVars(ctx context.Context, in *EnvVarsRequest, opts ...grpc.CallOption) (*EnvVarsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnvVarsResponse)
	err := c.cc.Invoke(ctx, EngineProvider_EnvVars_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineProviderServer is the server API for EngineProvider service.
// All implementations must embed UnimplementedEngineProviderServer
// for forward compatibility.
//
// EngineProvider is the lifecycle of one per-worktree engine instance.
type EngineProviderServer interface {
	// Up starts the engine listening on the host-allocated `ports`, with
	// its data directory anchored at `datadir`. The host passes
	// `worktree_root` so the plugin can resolve a `nix run` invocation
	// against the embedded flake without needing global state, and
	// `initial_resources` so the engine can self-provision (DB schemas,
	// kafka topics, minio buckets — engine-specific by `type`).
	Up(context.Context, *UpRequest) (*UpResponse, error)
	// Down asks the plugin to gracefully stop the instance and clean up
	// any supervisor processes it spawned.
	Down(context.Context, *DownRequest) (*DownResponse, error)
	// ReadyCheck polls for `timeout_sec` seconds until the instance
	// accepts connections on every entry in `ports`. Returns ready=true
	// only after the engine answers a protocol-level probe (not just
	// TCP listen); the conformance suite enforces this contract.
	ReadyCheck(context.Context, *ReadyCheckRequest) (*ReadyCheckResponse, error)
	// Cleanup removes the on-disk data directory after Down has
	// confirmed the instance is no longer running.
	Cleanup(context.Context, *CleanupRequest) (*CleanupResponse, error)
	// PortRangeDefault returns, per `role`, the [low, high] range the
	// plugin recommends. Single-port engines return one entry keyed
	// `"main"`; multi-port engines return one per role
	// (e.g. {"amqp": [...], "management": [...]} for rabbitmq).
	// Used when the YAML does not override `port_ranges`.
	PortRangeDefault(context.Context, *emptypb.Empty) (*PortRangeResponse, error)
	// EnvVars returns the set of environment variables consumers (the
	// host and any sibling repo) should see in their rendered .env.local.
	// For multi-port engines, role-suffixed keys are expected
	// (BOUGH_RABBITMQ_AMQP_PORT, BOUGH_RABBITMQ_MANAGEMENT_PORT, ...);
	// single-port engines keep the v0.3-era role-omitted form
	// (BOUGH_MYSQL_PORT).
	EnvVars(context.Context, *EnvVarsRequest) (*EnvVarsResponse, error)
	mustEmbedUnimplementedEngineProviderServer()
}

// UnimplementedEngineProviderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngineProviderServer struct{}

func (UnimplementedEngineProviderServer) Up(context.Context, *UpRequest) (*UpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Up not implemented")
}
func (UnimplementedEngineProviderServer) Down(context.Context, *DownRequest) (*DownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Down not implemented")
}
func (UnimplementedEngineProviderServer) ReadyCheck(context.Context, *ReadyCheckRequest) (*ReadyCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadyCheck not implemented")
}
func (UnimplementedEngineProviderServer) Cleanup(context.Context, *CleanupRequest) (*CleanupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cleanup not implemented")
}
func (UnimplementedEngineProviderServer) PortRangeDefault(context.Context, *emptypb.Empty) (*PortRangeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PortRangeDefault not implemented")
}
func (UnimplementedEngineProviderServer) EnvVars(context.Context, *EnvVarsRequest) (*EnvVarsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EnvVars not implemented")
}
func (UnimplementedEngineProviderServer) mustEmbedUnimplementedEngineProviderServer() {}
func (UnimplementedEngineProviderServer) testEmbeddedByValue()                        {}

// UnsafeEngineProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineProviderServer will
// result in compilation errors.
type UnsafeEngineProviderServer interface {
	mustEmbedUnimplementedEngineProviderServer()
}

func RegisterEngineProviderServer(s grpc.ServiceRegistrar, srv EngineProviderServer) {
	// If the following call panics, it indicates UnimplementedEngineProviderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EngineProvider_ServiceDesc, srv)
}

func _EngineProvider_Up_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineProviderServer).Up(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineProvider_Up_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineProviderServer).Up(ctx, req.(*UpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineProvider_Down_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineProviderServer).Down(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineProvider_Down_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineProviderServer).Down(ctx, req.(*DownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineProvider_ReadyCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadyCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineProviderServer).ReadyCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineProvider_ReadyCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineProviderServer).ReadyCheck(ctx, req.(*ReadyCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineProvider_Cleanup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineProviderServer).Cleanup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineProvider_Cleanup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineProviderServer).Cleanup(ctx, req.(*CleanupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineProvider_PortRangeDefault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineProviderServer).PortRangeDefault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineProvider_PortRangeDefault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineProviderServer).PortRangeDefault(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineProvider_EnvVars_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnvVarsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineProviderServer).EnvVars(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineProvider_EnvVars_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineProviderServer).EnvVars(ctx, req.(*EnvVarsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineProvider_ServiceDesc is the grpc.ServiceDesc for EngineProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bough.engine.v1.EngineProvider",
	HandlerType: (*EngineProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Up",
			Handler:    _EngineProvider_Up_Handler,
		},
		{
			MethodName: "Down",
			Handler:    _EngineProvider_Down_Handler,
		},
		{
			MethodName: "ReadyCheck",
			Handler:    _EngineProvider_ReadyCheck_Handler,
		},
		{
			MethodName: "Cleanup",
			Handler:    _EngineProvider_Cleanup_Handler,
		},
		{
			MethodName: "PortRangeDefault",
			Handler:    _EngineProvider_PortRangeDefault_Handler,
		},
		{
			MethodName: "EnvVars",
			Handler:    _EngineProvider_EnvVars_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}
