// engine.proto is the v0.4.0 contract between the bough host and any
// `bough-plugin-<kind>` binary that provisions a per-worktree engine
// instance (database / message broker / object store / search index /
// KV store, etc.). Plugins implement EngineProvider over Hashicorp
// go-plugin's gRPC transport.
//
// Renamed from db.proto in v0.4.0 along with `plugins/db/` →
// `plugins/engine/`. The shape was generalised: `Port int` →
// `repeated PortSpec ports` for multi-port engines (rabbitmq AMQP +
// Management, kafka broker + controller, NATS client + monitor),
// `repeated string initial_databases` → `repeated ResourceSpec
// initial_resources` (DB schema / kafka topic / minio bucket /
// rabbitmq vhost / consul KV). See docs/MIGRATION-v0.3-to-v0.4.md.
//
// Versioning: bumping ProtocolVersion in plugins/engine/api/handshake.go
// is what gates a backwards-incompatible change here. Add new fields
// with new tag numbers, do not renumber existing ones.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: engine.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PortSpec ties a port number to its semantic role inside an engine.
// Roles are engine-defined strings ("main" for single-port engines,
// "amqp" / "management" for rabbitmq, "broker" / "controller" for
// kafka, "client" / "monitor" / "cluster" for NATS, etc.). The host
// allocates one port per role declared by the engine's
// PortRangeDefault response (or by the YAML `port_ranges` override).
type PortSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortSpec) Reset() {
	*x = PortSpec{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortSpec) ProtoMessage() {}

func (x *PortSpec) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortSpec.ProtoReflect.Descriptor instead.
func (*PortSpec) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *PortSpec) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *PortSpec) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// ResourceSpec is one piece of state the engine should provision at
// Up time. `type` discriminates which kind of resource ("database",
// "topic", "bucket", "vhost", "kv", "index", ...) — the plugin
// silently drops types it does not implement. `params` is engine-
// specific tuning (kafka topic partitions, postgres schema encoding,
// etc.).
type ResourceSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Params        map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceSpec) Reset() {
	*x = ResourceSpec{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSpec) ProtoMessage() {}

func (x *ResourceSpec) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSpec.ProtoReflect.Descriptor instead.
func (*ResourceSpec) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *ResourceSpec) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceSpec) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

// PortRange is an inclusive [low, high] window from which the host's
// allocator picks deterministic-per-worktree ports.
type PortRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Low           int32                  `protobuf:"varint,1,opt,name=low,proto3" json:"low,omitempty"`
	High          int32                  `protobuf:"varint,2,opt,name=high,proto3" json:"high,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRange) Reset() {
	*x = PortRange{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRange) ProtoMessage() {}

func (x *PortRange) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRange.ProtoReflect.Descriptor instead.
func (*PortRange) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

func (x *PortRange) GetLow() int32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PortRange) GetHigh() int32 {
	if x != nil {
		return x.High
	}
	return 0
}

// PluginSpec is one plugin the host wants the engine to make available
// before it starts (e.g. an Elasticsearch analyzer). `id` and
// `location` mirror Elasticsearch's own `elasticsearch-plugins.yml`
// field names 1:1 — the elasticsearch plugin re-marshals this message
// directly into that file rather than inventing its own shape.
// `location` is required for unofficial/third-party plugins and empty
// for official ones the engine's own plugin registry already knows.
// A plugin that does not implement engine-managed plugins (mysql,
// redis, postgres, compose) silently ignores an empty or non-empty
// list either way.
type PluginSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginSpec) Reset() {
	*x = PluginSpec{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginSpec) ProtoMessage() {}

func (x *PluginSpec) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginSpec.ProtoReflect.Descriptor instead.
func (*PluginSpec) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *PluginSpec) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginSpec) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type UpRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ports            []*PortSpec            `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	Datadir          string                 `protobuf:"bytes,2,opt,name=datadir,proto3" json:"datadir,omitempty"`
	WorktreeRoot     string                 `protobuf:"bytes,3,opt,name=worktree_root,json=worktreeRoot,proto3" json:"worktree_root,omitempty"`
	SocketDir        string                 `protobuf:"bytes,4,opt,name=socket_dir,json=socketDir,proto3" json:"socket_dir,omitempty"`
	InitialResources []*ResourceSpec        `protobuf:"bytes,5,rep,name=initial_resources,json=initialResources,proto3" json:"initial_resources,omitempty"`
	Extras           map[string]string      `protobuf:"bytes,6,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Plugins          []*PluginSpec          `protobuf:"bytes,7,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpRequest) Reset() {
	*x = UpRequest{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpRequest) ProtoMessage() {}

func (x *UpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpRequest.ProtoReflect.Descriptor instead.
func (*UpRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *UpRequest) GetPorts() []*PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *UpRequest) GetDatadir() string {
	if x != nil {
		return x.Datadir
	}
	return ""
}

func (x *UpRequest) GetWorktreeRoot() string {
	if x != nil {
		return x.WorktreeRoot
	}
	return ""
}

func (x *UpRequest) GetSocketDir() string {
	if x != nil {
		return x.SocketDir
	}
	return ""
}

func (x *UpRequest) GetInitialResources() []*ResourceSpec {
	if x != nil {
		return x.InitialResources
	}
	return nil
}

func (x *UpRequest) GetExtras() map[string]string {
	if x != nil {
		return x.Extras
	}
	return nil
}

func (x *UpRequest) GetPlugins() []*PluginSpec {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// String error instead of gRPC status so plugins authored in non-Go
// languages can serialise a simple message without learning gRPC
// error codes. Empty string == success.
type UpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpResponse) Reset() {
	*x = UpResponse{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpResponse) ProtoMessage() {}

func (x *UpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpResponse.ProtoReflect.Descriptor instead.
func (*UpResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *UpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DownRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Ports              []int32                `protobuf:"varint,1,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	WorktreeRoot       string                 `protobuf:"bytes,2,opt,name=worktree_root,json=worktreeRoot,proto3" json:"worktree_root,omitempty"`
	GracefulTimeoutSec int32                  `protobuf:"varint,3,opt,name=graceful_timeout_sec,json=gracefulTimeoutSec,proto3" json:"graceful_timeout_sec,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownRequest) Reset() {
	*x = DownRequest{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownRequest) ProtoMessage() {}

func (x *DownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownRequest.ProtoReflect.Descriptor instead.
func (*DownRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *DownRequest) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *DownRequest) GetWorktreeRoot() string {
	if x != nil {
		return x.WorktreeRoot
	}
	return ""
}

func (x *DownRequest) GetGracefulTimeoutSec() int32 {
	if x != nil {
		return x.GracefulTimeoutSec
	}
	return 0
}

type DownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownResponse) Reset() {
	*x = DownResponse{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownResponse) ProtoMessage() {}

func (x *DownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownResponse.ProtoReflect.Descriptor instead.
func (*DownResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *DownResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ReadyCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ports         []int32                `protobuf:"varint,1,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	TimeoutSec    int32                  `protobuf:"varint,2,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyCheckRequest) Reset() {
	*x = ReadyCheckRequest{}
	mi := &file_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyCheckRequest) ProtoMessage() {}

func (x *ReadyCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyCheckRequest.ProtoReflect.Descriptor instead.
func (*ReadyCheckRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *ReadyCheckRequest) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ReadyCheckRequest) GetTimeoutSec() int32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

type ReadyCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ready         bool                   `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadyCheckResponse) Reset() {
	*x = ReadyCheckResponse{}
	mi := &file_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadyCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadyCheckResponse) ProtoMessage() {}

func (x *ReadyCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadyCheckResponse.ProtoReflect.Descriptor instead.
func (*ReadyCheckResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{9}
}

func (x *ReadyCheckResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ReadyCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CleanupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Datadir       string                 `protobuf:"bytes,1,opt,name=datadir,proto3" json:"datadir,omitempty"`
	Ports         []int32                `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupRequest) Reset() {
	*x = CleanupRequest{}
	mi := &file_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupRequest) ProtoMessage() {}

func (x *CleanupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupRequest.ProtoReflect.Descriptor instead.
func (*CleanupRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{10}
}

func (x *CleanupRequest) GetDatadir() string {
	if x != nil {
		return x.Datadir
	}
	return ""
}

func (x *CleanupRequest) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type CleanupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanupResponse) Reset() {
	*x = CleanupResponse{}
	mi := &file_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupResponse) ProtoMessage() {}

func (x *CleanupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupResponse.ProtoReflect.Descriptor instead.
func (*CleanupResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{11}
}

func (x *CleanupResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PortRangeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Keyed by role. Single-port engines return {"main": [low, high]}.
	Ranges        map[string]*PortRange `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortRangeResponse) Reset() {
	*x = PortRangeResponse{}
	mi := &file_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortRangeResponse) ProtoMessage() {}

func (x *PortRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortRangeResponse.ProtoReflect.Descriptor instead.
func (*PortRangeResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{12}
}

func (x *PortRangeResponse) GetRanges() map[string]*PortRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

type EnvVarsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Ports            []*PortSpec            `protobuf:"bytes,1,rep,name=ports,proto3" json:"ports,omitempty"`
	InitialResources []*ResourceSpec        `protobuf:"bytes,2,rep,name=initial_resources,json=initialResources,proto3" json:"initial_resources,omitempty"`
	SocketDir        string                 `protobuf:"bytes,3,opt,name=socket_dir,json=socketDir,proto3" json:"socket_dir,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EnvVarsRequest) Reset() {
	*x = EnvVarsRequest{}
	mi := &file_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVarsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVarsRequest) ProtoMessage() {}

func (x *EnvVarsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVarsRequest.ProtoReflect.Descriptor instead.
func (*EnvVarsRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{13}
}

func (x *EnvVarsRequest) GetPorts() []*PortSpec {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *EnvVarsRequest) GetInitialResources() []*ResourceSpec {
	if x != nil {
		return x.InitialResources
	}
	return nil
}

func (x *EnvVarsRequest) GetSocketDir() string {
	if x != nil {
		return x.SocketDir
	}
	return ""
}

type EnvVarsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vars          map[string]string      `protobuf:"bytes,1,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVarsResponse) Reset() {
	*x = EnvVarsResponse{}
	mi := &file_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVarsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVarsResponse) ProtoMessage() {}

func (x *EnvVarsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVarsResponse.ProtoReflect.Descriptor instead.
func (*EnvVarsResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{14}
}

func (x *EnvVarsResponse) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x0fbough.engine.v1\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\bPortSpec\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"\xb4\x01\n" +
	"\fResourceSpec\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12A\n" +
	"\x06params\x18\x03 \x03(\v2).bough.engine.v1.ResourceSpec.ParamsEntryR\x06params\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\tPortRange\x12\x10\n" +
	"\x03low\x18\x01 \x01(\x05R\x03low\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x05R\x04high\"8\n" +
	"\n" +
	"PluginSpec\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\x98\x03\n" +
	"\tUpRequest\x12/\n" +
	"\x05ports\x18\x01 \x03(\v2\x19.bough.engine.v1.PortSpecR\x05ports\x12\x18\n" +
	"\adatadir\x18\x02 \x01(\tR\adatadir\x12#\n" +
	"\rworktree_root\x18\x03 \x01(\tR\fworktreeRoot\x12\x1d\n" +
	"\n" +
	"socket_dir\x18\x04 \x01(\tR\tsocketDir\x12J\n" +
	"\x11initial_resources\x18\x05 \x03(\v2\x1d.bough.engine.v1.ResourceSpecR\x10initialResources\x12>\n" +
	"\x06extras\x18\x06 \x03(\v2&.bough.engine.v1.UpRequest.ExtrasEntryR\x06extras\x125\n" +
	"\aplugins\x18\a \x03(\v2\x1b.bough.engine.v1.PluginSpecR\aplugins\x1a9\n" +
	"\vExtrasEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\"\n" +
	"\n" +
	"UpResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"z\n" +
	"\vDownRequest\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\x05R\x05ports\x12#\n" +
	"\rworktree_root\x18\x02 \x01(\tR\fworktreeRoot\x120\n" +
	"\x14graceful_timeout_sec\x18\x03 \x01(\x05R\x12gracefulTimeoutSec\"$\n" +
	"\fDownResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"J\n" +
	"\x11ReadyCheckRequest\x12\x14\n" +
	"\x05ports\x18\x01 \x03(\x05R\x05ports\x12\x1f\n" +
	"\vtimeout_sec\x18\x02 \x01(\x05R\n" +
	"timeoutSec\"@\n" +
	"\x12ReadyCheckResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"@\n" +
	"\x0eCleanupRequest\x12\x18\n" +
	"\adatadir\x18\x01 \x01(\tR\adatadir\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\x05R\x05ports\"'\n" +
	"\x0fCleanupResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xb2\x01\n" +
	"\x11PortRangeResponse\x12F\n" +
	"\x06ranges\x18\x01 \x03(\v2..bough.engine.v1.PortRangeResponse.RangesEntryR\x06ranges\x1aU\n" +
	"\vRangesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.bough.engine.v1.PortRangeR\x05value:\x028\x01\"\xac\x01\n" +
	"\x0eEnvVarsRequest\x12/\n" +
	"\x05ports\x18\x01 \x03(\v2\x19.bough.engine.v1.PortSpecR\x05ports\x12J\n" +
	"\x11initial_resources\x18\x02 \x03(\v2\x1d.bough.engine.v1.ResourceSpecR\x10initialResources\x12\x1d\n" +
	"\n" +
	"socket_dir\x18\x03 \x01(\tR\tsocketDir\"\x8a\x01\n" +
	"\x0fEnvVarsResponse\x12>\n" +
	"\x04vars\x18\x01 \x03(\v2*.bough.engine.v1.EnvVarsResponse.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xd7\x03\n" +
	"\x0eEngineProvider\x12=\n" +
	"\x02Up\x12\x1a.bough.engine.v1.UpRequest\x1a\x1b.bough.engine.v1.UpResponse\x12C\n" +
	"\x04Down\x12\x1c.bough.engine.v1.DownRequest\x1a\x1d.bough.engine.v1.DownResponse\x12U\n" +
	"\n" +
	"ReadyCheck\x12\".bough.engine.v1.ReadyCheckRequest\x1a#.bough.engine.v1.ReadyCheckResponse\x12L\n" +
	"\aCleanup\x12\x1f.bough.engine.v1.CleanupRequest\x1a .bough.engine.v1.CleanupResponse\x12N\n" +
	"\x10PortRangeDefault\x12\x16.google.protobuf.Empty\x1a\".bough.engine.v1.PortRangeResponse\x12L\n" +
	"\aEnvVars\x12\x1f.bough.engine.v1.EnvVarsRequest\x1a .bough.engine.v1.EnvVarsResponseB;Z9github.com/ikeikeikeike/bough/plugins/engine/api/proto;pbb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_engine_proto_goTypes = []any{
	(*PortSpec)(nil),           // 0: bough.engine.v1.PortSpec
	(*ResourceSpec)(nil),       // 1: bough.engine.v1.ResourceSpec
	(*PortRange)(nil),          // 2: bough.engine.v1.PortRange
	(*PluginSpec)(nil),         // 3: bough.engine.v1.PluginSpec
	(*UpRequest)(nil),          // 4: bough.engine.v1.UpRequest
	(*UpResponse)(nil),         // 5: bough.engine.v1.UpResponse
	(*DownRequest)(nil),        // 6: bough.engine.v1.DownRequest
	(*DownResponse)(nil),       // 7: bough.engine.v1.DownResponse
	(*ReadyCheckRequest)(nil),  // 8: bough.engine.v1.ReadyCheckRequest
	(*ReadyCheckResponse)(nil), // 9: bough.engine.v1.ReadyCheckResponse
	(*CleanupRequest)(nil),     // 10: bough.engine.v1.CleanupRequest
	(*CleanupResponse)(nil),    // 11: bough.engine.v1.CleanupResponse
	(*PortRangeResponse)(nil),  // 12: bough.engine.v1.PortRangeResponse
	(*EnvVarsRequest)(nil),     // 13: bough.engine.v1.EnvVarsRequest
	(*EnvVarsResponse)(nil),    // 14: bough.engine.v1.EnvVarsResponse
	nil,                        // 15: bough.engine.v1.ResourceSpec.ParamsEntry
	nil,                        // 16: bough.engine.v1.UpRequest.ExtrasEntry
	nil,                        // 17: bough.engine.v1.PortRangeResponse.RangesEntry
	nil,                        // 18: bough.engine.v1.EnvVarsResponse.VarsEntry
	(*emptypb.Empty)(nil),      // 19: google.protobuf.Empty
}
var file_engine_proto_depIdxs = []int32{
	15, // 0: bough.engine.v1.ResourceSpec.params:type_name -> bough.engine.v1.ResourceSpec.ParamsEntry
	0,  // 1: bough.engine.v1.UpRequest.ports:type_name -> bough.engine.v1.PortSpec
	1,  // 2: bough.engine.v1.UpRequest.initial_resources:type_name -> bough.engine.v1.ResourceSpec
	16, // 3: bough.engine.v1.UpRequest.extras:type_name -> bough.engine.v1.UpRequest.ExtrasEntry
	3,  // 4: bough.engine.v1.UpRequest.plugins:type_name -> bough.engine.v1.PluginSpec
	17, // 5: bough.engine.v1.PortRangeResponse.ranges:type_name -> bough.engine.v1.PortRangeResponse.RangesEntry
	0,  // 6: bough.engine.v1.EnvVarsRequest.ports:type_name -> bough.engine.v1.PortSpec
	1,  // 7: bough.engine.v1.EnvVarsRequest.initial_resources:type_name -> bough.engine.v1.ResourceSpec
	18, // 8: bough.engine.v1.EnvVarsResponse.vars:type_name -> bough.engine.v1.EnvVarsResponse.VarsEntry
	2,  // 9: bough.engine.v1.PortRangeResponse.RangesEntry.value:type_name -> bough.engine.v1.PortRange
	4,  // 10: bough.engine.v1.EngineProvider.Up:input_type -> bough.engine.v1.UpRequest
	6,  // 11: bough.engine.v1.EngineProvider.Down:input_type -> bough.engine.v1.DownRequest
	8,  // 12: bough.engine.v1.EngineProvider.ReadyCheck:input_type -> bough.engine.v1.ReadyCheckRequest
	10, // 13: bough.engine.v1.EngineProvider.Cleanup:input_type -> bough.engine.v1.CleanupRequest
	19, // 14: bough.engine.v1.EngineProvider.PortRangeDefault:input_type -> google.protobuf.Empty
	13, // 15: bough.engine.v1.EngineProvider.EnvVars:input_type -> bough.engine.v1.EnvVarsRequest
	5,  // 16: bough.engine.v1.EngineProvider.Up:output_type -> bough.engine.v1.UpResponse
	7,  // 17: bough.engine.v1.EngineProvider.Down:output_type -> bough.engine.v1.DownResponse
	9,  // 18: bough.engine.v1.EngineProvider.ReadyCheck:output_type -> bough.engine.v1.ReadyCheckResponse
	11, // 19: bough.engine.v1.EngineProvider.Cleanup:output_type -> bough.engine.v1.CleanupResponse
	12, // 20: bough.engine.v1.EngineProvider.PortRangeDefault:output_type -> bough.engine.v1.PortRangeResponse
	14, // 21: bough.engine.v1.EngineProvider.EnvVars:output_type -> bough.engine.v1.EnvVarsResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
